/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms.tables.records;


import com.gvdroid.simple.jooq.code.sms.tables.SmsUserMast;
import com.gvdroid.simple.jooq.code.sms.tables.interfaces.ISmsUserMast;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 权限-用户主表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SmsUserMastRecord extends UpdatableRecordImpl<SmsUserMastRecord> implements Record19<Long, String, Integer, String, String, String, String, String, LocalDateTime, Integer, Boolean, LocalDateTime, String, String, LocalDateTime, String, String, Integer, String>, ISmsUserMast {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sms.sms_user_mast.id</code>. 主键（用户编号）
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.id</code>. 主键（用户编号）
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>sms.sms_user_mast.name</code>. 用户名称
     */
    @Override
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.name</code>. 用户名称
     */
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sms.sms_user_mast.category</code>. 用户分类 1 user, 2 customer
     */
    @Override
    public void setCategory(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.category</code>. 用户分类 1 user, 2 customer
     */
    @Override
    public Integer getCategory() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sms.sms_user_mast.customerId</code>. 用户客户编号
     */
    @Override
    public void setCustomerid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.customerId</code>. 用户客户编号
     */
    @Override
    public String getCustomerid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sms.sms_user_mast.accountNo</code>. 商户虚拟账号
     */
    @Override
    public void setAccountno(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.accountNo</code>. 商户虚拟账号
     */
    @Override
    public String getAccountno() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sms.sms_user_mast.mobile</code>. 用户手机号码
     */
    @Override
    public void setMobile(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.mobile</code>. 用户手机号码
     */
    @Override
    public String getMobile() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sms.sms_user_mast.source</code>. 用户来源 added, invited, machine
     */
    @Override
    public void setSource(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.source</code>. 用户来源 added, invited, machine
     */
    @Override
    public String getSource() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sms.sms_user_mast.pinCode</code>. 验证码
     */
    @Override
    public void setPincode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.pinCode</code>. 验证码
     */
    @Override
    public String getPincode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>sms.sms_user_mast.pinCodeDate</code>. 验证码时间
     */
    @Override
    public void setPincodedate(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.pinCodeDate</code>. 验证码时间
     */
    @Override
    public LocalDateTime getPincodedate() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>sms.sms_user_mast.status</code>. 状态 1 normal
     */
    @Override
    public void setStatus(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.status</code>. 状态 1 normal
     */
    @Override
    public Integer getStatus() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>sms.sms_user_mast.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    @Override
    public void setDeleted(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    @Override
    public Boolean getDeleted() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>sms.sms_user_mast.createDate</code>. 创建时间
     */
    @Override
    public void setCreatedate(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.createDate</code>. 创建时间
     */
    @Override
    public LocalDateTime getCreatedate() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>sms.sms_user_mast.createUser</code>. 创建人员
     */
    @Override
    public void setCreateuser(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.createUser</code>. 创建人员
     */
    @Override
    public String getCreateuser() {
        return (String) get(12);
    }

    /**
     * Setter for <code>sms.sms_user_mast.createOrg</code>. 创建机构
     */
    @Override
    public void setCreateorg(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.createOrg</code>. 创建机构
     */
    @Override
    public String getCreateorg() {
        return (String) get(13);
    }

    /**
     * Setter for <code>sms.sms_user_mast.updateDate</code>. 维护时间
     */
    @Override
    public void setUpdatedate(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.updateDate</code>. 维护时间
     */
    @Override
    public LocalDateTime getUpdatedate() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>sms.sms_user_mast.updateUser</code>. 维护人员
     */
    @Override
    public void setUpdateuser(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.updateUser</code>. 维护人员
     */
    @Override
    public String getUpdateuser() {
        return (String) get(15);
    }

    /**
     * Setter for <code>sms.sms_user_mast.updateOrg</code>. 维护机构
     */
    @Override
    public void setUpdateorg(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.updateOrg</code>. 维护机构
     */
    @Override
    public String getUpdateorg() {
        return (String) get(16);
    }

    /**
     * Setter for <code>sms.sms_user_mast.updateNo</code>. 维护序号
     */
    @Override
    public void setUpdateno(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.updateNo</code>. 维护序号
     */
    @Override
    public Integer getUpdateno() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>sms.sms_user_mast.entityId</code>. 所属实体
     */
    @Override
    public void setEntityid(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>sms.sms_user_mast.entityId</code>. 所属实体
     */
    @Override
    public String getEntityid() {
        return (String) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<Long, String, Integer, String, String, String, String, String, LocalDateTime, Integer, Boolean, LocalDateTime, String, String, LocalDateTime, String, String, Integer, String> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<Long, String, Integer, String, String, String, String, String, LocalDateTime, Integer, Boolean, LocalDateTime, String, String, LocalDateTime, String, String, Integer, String> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SmsUserMast.SMS_USER_MAST.ID;
    }

    @Override
    public Field<String> field2() {
        return SmsUserMast.SMS_USER_MAST.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return SmsUserMast.SMS_USER_MAST.CATEGORY;
    }

    @Override
    public Field<String> field4() {
        return SmsUserMast.SMS_USER_MAST.CUSTOMERID;
    }

    @Override
    public Field<String> field5() {
        return SmsUserMast.SMS_USER_MAST.ACCOUNTNO;
    }

    @Override
    public Field<String> field6() {
        return SmsUserMast.SMS_USER_MAST.MOBILE;
    }

    @Override
    public Field<String> field7() {
        return SmsUserMast.SMS_USER_MAST.SOURCE;
    }

    @Override
    public Field<String> field8() {
        return SmsUserMast.SMS_USER_MAST.PINCODE;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return SmsUserMast.SMS_USER_MAST.PINCODEDATE;
    }

    @Override
    public Field<Integer> field10() {
        return SmsUserMast.SMS_USER_MAST.STATUS;
    }

    @Override
    public Field<Boolean> field11() {
        return SmsUserMast.SMS_USER_MAST.DELETED;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return SmsUserMast.SMS_USER_MAST.CREATEDATE;
    }

    @Override
    public Field<String> field13() {
        return SmsUserMast.SMS_USER_MAST.CREATEUSER;
    }

    @Override
    public Field<String> field14() {
        return SmsUserMast.SMS_USER_MAST.CREATEORG;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return SmsUserMast.SMS_USER_MAST.UPDATEDATE;
    }

    @Override
    public Field<String> field16() {
        return SmsUserMast.SMS_USER_MAST.UPDATEUSER;
    }

    @Override
    public Field<String> field17() {
        return SmsUserMast.SMS_USER_MAST.UPDATEORG;
    }

    @Override
    public Field<Integer> field18() {
        return SmsUserMast.SMS_USER_MAST.UPDATENO;
    }

    @Override
    public Field<String> field19() {
        return SmsUserMast.SMS_USER_MAST.ENTITYID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getCategory();
    }

    @Override
    public String component4() {
        return getCustomerid();
    }

    @Override
    public String component5() {
        return getAccountno();
    }

    @Override
    public String component6() {
        return getMobile();
    }

    @Override
    public String component7() {
        return getSource();
    }

    @Override
    public String component8() {
        return getPincode();
    }

    @Override
    public LocalDateTime component9() {
        return getPincodedate();
    }

    @Override
    public Integer component10() {
        return getStatus();
    }

    @Override
    public Boolean component11() {
        return getDeleted();
    }

    @Override
    public LocalDateTime component12() {
        return getCreatedate();
    }

    @Override
    public String component13() {
        return getCreateuser();
    }

    @Override
    public String component14() {
        return getCreateorg();
    }

    @Override
    public LocalDateTime component15() {
        return getUpdatedate();
    }

    @Override
    public String component16() {
        return getUpdateuser();
    }

    @Override
    public String component17() {
        return getUpdateorg();
    }

    @Override
    public Integer component18() {
        return getUpdateno();
    }

    @Override
    public String component19() {
        return getEntityid();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getCategory();
    }

    @Override
    public String value4() {
        return getCustomerid();
    }

    @Override
    public String value5() {
        return getAccountno();
    }

    @Override
    public String value6() {
        return getMobile();
    }

    @Override
    public String value7() {
        return getSource();
    }

    @Override
    public String value8() {
        return getPincode();
    }

    @Override
    public LocalDateTime value9() {
        return getPincodedate();
    }

    @Override
    public Integer value10() {
        return getStatus();
    }

    @Override
    public Boolean value11() {
        return getDeleted();
    }

    @Override
    public LocalDateTime value12() {
        return getCreatedate();
    }

    @Override
    public String value13() {
        return getCreateuser();
    }

    @Override
    public String value14() {
        return getCreateorg();
    }

    @Override
    public LocalDateTime value15() {
        return getUpdatedate();
    }

    @Override
    public String value16() {
        return getUpdateuser();
    }

    @Override
    public String value17() {
        return getUpdateorg();
    }

    @Override
    public Integer value18() {
        return getUpdateno();
    }

    @Override
    public String value19() {
        return getEntityid();
    }

    @Override
    public SmsUserMastRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SmsUserMastRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SmsUserMastRecord value3(Integer value) {
        setCategory(value);
        return this;
    }

    @Override
    public SmsUserMastRecord value4(String value) {
        setCustomerid(value);
        return this;
    }

    @Override
    public SmsUserMastRecord value5(String value) {
        setAccountno(value);
        return this;
    }

    @Override
    public SmsUserMastRecord value6(String value) {
        setMobile(value);
        return this;
    }

    @Override
    public SmsUserMastRecord value7(String value) {
        setSource(value);
        return this;
    }

    @Override
    public SmsUserMastRecord value8(String value) {
        setPincode(value);
        return this;
    }

    @Override
    public SmsUserMastRecord value9(LocalDateTime value) {
        setPincodedate(value);
        return this;
    }

    @Override
    public SmsUserMastRecord value10(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public SmsUserMastRecord value11(Boolean value) {
        setDeleted(value);
        return this;
    }

    @Override
    public SmsUserMastRecord value12(LocalDateTime value) {
        setCreatedate(value);
        return this;
    }

    @Override
    public SmsUserMastRecord value13(String value) {
        setCreateuser(value);
        return this;
    }

    @Override
    public SmsUserMastRecord value14(String value) {
        setCreateorg(value);
        return this;
    }

    @Override
    public SmsUserMastRecord value15(LocalDateTime value) {
        setUpdatedate(value);
        return this;
    }

    @Override
    public SmsUserMastRecord value16(String value) {
        setUpdateuser(value);
        return this;
    }

    @Override
    public SmsUserMastRecord value17(String value) {
        setUpdateorg(value);
        return this;
    }

    @Override
    public SmsUserMastRecord value18(Integer value) {
        setUpdateno(value);
        return this;
    }

    @Override
    public SmsUserMastRecord value19(String value) {
        setEntityid(value);
        return this;
    }

    @Override
    public SmsUserMastRecord values(Long value1, String value2, Integer value3, String value4, String value5, String value6, String value7, String value8, LocalDateTime value9, Integer value10, Boolean value11, LocalDateTime value12, String value13, String value14, LocalDateTime value15, String value16, String value17, Integer value18, String value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ISmsUserMast from) {
        setId(from.getId());
        setName(from.getName());
        setCategory(from.getCategory());
        setCustomerid(from.getCustomerid());
        setAccountno(from.getAccountno());
        setMobile(from.getMobile());
        setSource(from.getSource());
        setPincode(from.getPincode());
        setPincodedate(from.getPincodedate());
        setStatus(from.getStatus());
        setDeleted(from.getDeleted());
        setCreatedate(from.getCreatedate());
        setCreateuser(from.getCreateuser());
        setCreateorg(from.getCreateorg());
        setUpdatedate(from.getUpdatedate());
        setUpdateuser(from.getUpdateuser());
        setUpdateorg(from.getUpdateorg());
        setUpdateno(from.getUpdateno());
        setEntityid(from.getEntityid());
    }

    @Override
    public <E extends ISmsUserMast> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SmsUserMastRecord
     */
    public SmsUserMastRecord() {
        super(SmsUserMast.SMS_USER_MAST);
    }

    /**
     * Create a detached, initialised SmsUserMastRecord
     */
    public SmsUserMastRecord(Long id, String name, Integer category, String customerid, String accountno, String mobile, String source, String pincode, LocalDateTime pincodedate, Integer status, Boolean deleted, LocalDateTime createdate, String createuser, String createorg, LocalDateTime updatedate, String updateuser, String updateorg, Integer updateno, String entityid) {
        super(SmsUserMast.SMS_USER_MAST);

        setId(id);
        setName(name);
        setCategory(category);
        setCustomerid(customerid);
        setAccountno(accountno);
        setMobile(mobile);
        setSource(source);
        setPincode(pincode);
        setPincodedate(pincodedate);
        setStatus(status);
        setDeleted(deleted);
        setCreatedate(createdate);
        setCreateuser(createuser);
        setCreateorg(createorg);
        setUpdatedate(updatedate);
        setUpdateuser(updateuser);
        setUpdateorg(updateorg);
        setUpdateno(updateno);
        setEntityid(entityid);
    }
}
