/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms.tables.records;


import com.gvdroid.simple.jooq.code.sms.tables.SmsUserGroupXref;
import com.gvdroid.simple.jooq.code.sms.tables.interfaces.ISmsUserGroupXref;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 权限-用户用户组关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SmsUserGroupXrefRecord extends UpdatableRecordImpl<SmsUserGroupXrefRecord> implements Record14<Long, Long, Long, Boolean, Integer, Boolean, LocalDateTime, String, String, LocalDateTime, String, String, Integer, String>, ISmsUserGroupXref {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sms.sms_user_group_xref.id</code>. 主键
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>sms.sms_user_group_xref.id</code>. 主键
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>sms.sms_user_group_xref.userId</code>. 用户编号
     */
    @Override
    public void setUserid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>sms.sms_user_group_xref.userId</code>. 用户编号
     */
    @Override
    public Long getUserid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>sms.sms_user_group_xref.groupId</code>. 用户组编号
     */
    @Override
    public void setGroupid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>sms.sms_user_group_xref.groupId</code>. 用户组编号
     */
    @Override
    public Long getGroupid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>sms.sms_user_group_xref.defaulted</code>. 默认所属机构 0 非所属机构 1 所属机构
     */
    @Override
    public void setDefaulted(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>sms.sms_user_group_xref.defaulted</code>. 默认所属机构 0 非所属机构 1 所属机构
     */
    @Override
    public Boolean getDefaulted() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>sms.sms_user_group_xref.status</code>. 状态 1 normal
     */
    @Override
    public void setStatus(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>sms.sms_user_group_xref.status</code>. 状态 1 normal
     */
    @Override
    public Integer getStatus() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>sms.sms_user_group_xref.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    @Override
    public void setDeleted(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>sms.sms_user_group_xref.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    @Override
    public Boolean getDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>sms.sms_user_group_xref.createDate</code>. 创建时间
     */
    @Override
    public void setCreatedate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>sms.sms_user_group_xref.createDate</code>. 创建时间
     */
    @Override
    public LocalDateTime getCreatedate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>sms.sms_user_group_xref.createUser</code>. 创建人员
     */
    @Override
    public void setCreateuser(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>sms.sms_user_group_xref.createUser</code>. 创建人员
     */
    @Override
    public String getCreateuser() {
        return (String) get(7);
    }

    /**
     * Setter for <code>sms.sms_user_group_xref.createOrg</code>. 创建机构
     */
    @Override
    public void setCreateorg(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>sms.sms_user_group_xref.createOrg</code>. 创建机构
     */
    @Override
    public String getCreateorg() {
        return (String) get(8);
    }

    /**
     * Setter for <code>sms.sms_user_group_xref.updateDate</code>. 维护时间
     */
    @Override
    public void setUpdatedate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>sms.sms_user_group_xref.updateDate</code>. 维护时间
     */
    @Override
    public LocalDateTime getUpdatedate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>sms.sms_user_group_xref.updateUser</code>. 维护人员
     */
    @Override
    public void setUpdateuser(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>sms.sms_user_group_xref.updateUser</code>. 维护人员
     */
    @Override
    public String getUpdateuser() {
        return (String) get(10);
    }

    /**
     * Setter for <code>sms.sms_user_group_xref.updateOrg</code>. 维护机构
     */
    @Override
    public void setUpdateorg(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>sms.sms_user_group_xref.updateOrg</code>. 维护机构
     */
    @Override
    public String getUpdateorg() {
        return (String) get(11);
    }

    /**
     * Setter for <code>sms.sms_user_group_xref.updateNo</code>. 维护序号
     */
    @Override
    public void setUpdateno(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>sms.sms_user_group_xref.updateNo</code>. 维护序号
     */
    @Override
    public Integer getUpdateno() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>sms.sms_user_group_xref.entityId</code>. 所属实体
     */
    @Override
    public void setEntityid(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>sms.sms_user_group_xref.entityId</code>. 所属实体
     */
    @Override
    public String getEntityid() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, Long, Long, Boolean, Integer, Boolean, LocalDateTime, String, String, LocalDateTime, String, String, Integer, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, Long, Long, Boolean, Integer, Boolean, LocalDateTime, String, String, LocalDateTime, String, String, Integer, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SmsUserGroupXref.SMS_USER_GROUP_XREF.ID;
    }

    @Override
    public Field<Long> field2() {
        return SmsUserGroupXref.SMS_USER_GROUP_XREF.USERID;
    }

    @Override
    public Field<Long> field3() {
        return SmsUserGroupXref.SMS_USER_GROUP_XREF.GROUPID;
    }

    @Override
    public Field<Boolean> field4() {
        return SmsUserGroupXref.SMS_USER_GROUP_XREF.DEFAULTED;
    }

    @Override
    public Field<Integer> field5() {
        return SmsUserGroupXref.SMS_USER_GROUP_XREF.STATUS;
    }

    @Override
    public Field<Boolean> field6() {
        return SmsUserGroupXref.SMS_USER_GROUP_XREF.DELETED;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return SmsUserGroupXref.SMS_USER_GROUP_XREF.CREATEDATE;
    }

    @Override
    public Field<String> field8() {
        return SmsUserGroupXref.SMS_USER_GROUP_XREF.CREATEUSER;
    }

    @Override
    public Field<String> field9() {
        return SmsUserGroupXref.SMS_USER_GROUP_XREF.CREATEORG;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return SmsUserGroupXref.SMS_USER_GROUP_XREF.UPDATEDATE;
    }

    @Override
    public Field<String> field11() {
        return SmsUserGroupXref.SMS_USER_GROUP_XREF.UPDATEUSER;
    }

    @Override
    public Field<String> field12() {
        return SmsUserGroupXref.SMS_USER_GROUP_XREF.UPDATEORG;
    }

    @Override
    public Field<Integer> field13() {
        return SmsUserGroupXref.SMS_USER_GROUP_XREF.UPDATENO;
    }

    @Override
    public Field<String> field14() {
        return SmsUserGroupXref.SMS_USER_GROUP_XREF.ENTITYID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserid();
    }

    @Override
    public Long component3() {
        return getGroupid();
    }

    @Override
    public Boolean component4() {
        return getDefaulted();
    }

    @Override
    public Integer component5() {
        return getStatus();
    }

    @Override
    public Boolean component6() {
        return getDeleted();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedate();
    }

    @Override
    public String component8() {
        return getCreateuser();
    }

    @Override
    public String component9() {
        return getCreateorg();
    }

    @Override
    public LocalDateTime component10() {
        return getUpdatedate();
    }

    @Override
    public String component11() {
        return getUpdateuser();
    }

    @Override
    public String component12() {
        return getUpdateorg();
    }

    @Override
    public Integer component13() {
        return getUpdateno();
    }

    @Override
    public String component14() {
        return getEntityid();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserid();
    }

    @Override
    public Long value3() {
        return getGroupid();
    }

    @Override
    public Boolean value4() {
        return getDefaulted();
    }

    @Override
    public Integer value5() {
        return getStatus();
    }

    @Override
    public Boolean value6() {
        return getDeleted();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedate();
    }

    @Override
    public String value8() {
        return getCreateuser();
    }

    @Override
    public String value9() {
        return getCreateorg();
    }

    @Override
    public LocalDateTime value10() {
        return getUpdatedate();
    }

    @Override
    public String value11() {
        return getUpdateuser();
    }

    @Override
    public String value12() {
        return getUpdateorg();
    }

    @Override
    public Integer value13() {
        return getUpdateno();
    }

    @Override
    public String value14() {
        return getEntityid();
    }

    @Override
    public SmsUserGroupXrefRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SmsUserGroupXrefRecord value2(Long value) {
        setUserid(value);
        return this;
    }

    @Override
    public SmsUserGroupXrefRecord value3(Long value) {
        setGroupid(value);
        return this;
    }

    @Override
    public SmsUserGroupXrefRecord value4(Boolean value) {
        setDefaulted(value);
        return this;
    }

    @Override
    public SmsUserGroupXrefRecord value5(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public SmsUserGroupXrefRecord value6(Boolean value) {
        setDeleted(value);
        return this;
    }

    @Override
    public SmsUserGroupXrefRecord value7(LocalDateTime value) {
        setCreatedate(value);
        return this;
    }

    @Override
    public SmsUserGroupXrefRecord value8(String value) {
        setCreateuser(value);
        return this;
    }

    @Override
    public SmsUserGroupXrefRecord value9(String value) {
        setCreateorg(value);
        return this;
    }

    @Override
    public SmsUserGroupXrefRecord value10(LocalDateTime value) {
        setUpdatedate(value);
        return this;
    }

    @Override
    public SmsUserGroupXrefRecord value11(String value) {
        setUpdateuser(value);
        return this;
    }

    @Override
    public SmsUserGroupXrefRecord value12(String value) {
        setUpdateorg(value);
        return this;
    }

    @Override
    public SmsUserGroupXrefRecord value13(Integer value) {
        setUpdateno(value);
        return this;
    }

    @Override
    public SmsUserGroupXrefRecord value14(String value) {
        setEntityid(value);
        return this;
    }

    @Override
    public SmsUserGroupXrefRecord values(Long value1, Long value2, Long value3, Boolean value4, Integer value5, Boolean value6, LocalDateTime value7, String value8, String value9, LocalDateTime value10, String value11, String value12, Integer value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ISmsUserGroupXref from) {
        setId(from.getId());
        setUserid(from.getUserid());
        setGroupid(from.getGroupid());
        setDefaulted(from.getDefaulted());
        setStatus(from.getStatus());
        setDeleted(from.getDeleted());
        setCreatedate(from.getCreatedate());
        setCreateuser(from.getCreateuser());
        setCreateorg(from.getCreateorg());
        setUpdatedate(from.getUpdatedate());
        setUpdateuser(from.getUpdateuser());
        setUpdateorg(from.getUpdateorg());
        setUpdateno(from.getUpdateno());
        setEntityid(from.getEntityid());
    }

    @Override
    public <E extends ISmsUserGroupXref> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SmsUserGroupXrefRecord
     */
    public SmsUserGroupXrefRecord() {
        super(SmsUserGroupXref.SMS_USER_GROUP_XREF);
    }

    /**
     * Create a detached, initialised SmsUserGroupXrefRecord
     */
    public SmsUserGroupXrefRecord(Long id, Long userid, Long groupid, Boolean defaulted, Integer status, Boolean deleted, LocalDateTime createdate, String createuser, String createorg, LocalDateTime updatedate, String updateuser, String updateorg, Integer updateno, String entityid) {
        super(SmsUserGroupXref.SMS_USER_GROUP_XREF);

        setId(id);
        setUserid(userid);
        setGroupid(groupid);
        setDefaulted(defaulted);
        setStatus(status);
        setDeleted(deleted);
        setCreatedate(createdate);
        setCreateuser(createuser);
        setCreateorg(createorg);
        setUpdatedate(updatedate);
        setUpdateuser(updateuser);
        setUpdateorg(updateorg);
        setUpdateno(updateno);
        setEntityid(entityid);
    }
}
