/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 权限-用户登陆凭证
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISmsUserPassport extends Serializable {

    /**
     * Setter for <code>sms.sms_user_passport.id</code>. 主键
     */
    public void setId(Long value);

    /**
     * Getter for <code>sms.sms_user_passport.id</code>. 主键
     */
    public Long getId();

    /**
     * Setter for <code>sms.sms_user_passport.userId</code>. 用户编号
     */
    public void setUserid(Long value);

    /**
     * Getter for <code>sms.sms_user_passport.userId</code>. 用户编号
     */
    public Long getUserid();

    /**
     * Setter for <code>sms.sms_user_passport.passportType</code>. 账号类型 account, weixin, qq, weibo, jd, github
     */
    public void setPassporttype(String value);

    /**
     * Getter for <code>sms.sms_user_passport.passportType</code>. 账号类型 account, weixin, qq, weibo, jd, github
     */
    public String getPassporttype();

    /**
     * Setter for <code>sms.sms_user_passport.passportNo</code>. 登录账号
     */
    public void setPassportno(String value);

    /**
     * Getter for <code>sms.sms_user_passport.passportNo</code>. 登录账号
     */
    public String getPassportno();

    /**
     * Setter for <code>sms.sms_user_passport.saltCode</code>. 混淆码
     */
    public void setSaltcode(String value);

    /**
     * Getter for <code>sms.sms_user_passport.saltCode</code>. 混淆码
     */
    public String getSaltcode();

    /**
     * Setter for <code>sms.sms_user_passport.password</code>. 登录密码
     */
    public void setPassword(String value);

    /**
     * Getter for <code>sms.sms_user_passport.password</code>. 登录密码
     */
    public String getPassword();

    /**
     * Setter for <code>sms.sms_user_passport.lastLoginDate</code>. 上次登录时间
     */
    public void setLastlogindate(LocalDateTime value);

    /**
     * Getter for <code>sms.sms_user_passport.lastLoginDate</code>. 上次登录时间
     */
    public LocalDateTime getLastlogindate();

    /**
     * Setter for <code>sms.sms_user_passport.status</code>. 状态 1 normal
     */
    public void setStatus(Integer value);

    /**
     * Getter for <code>sms.sms_user_passport.status</code>. 状态 1 normal
     */
    public Integer getStatus();

    /**
     * Setter for <code>sms.sms_user_passport.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    public void setDeleted(Boolean value);

    /**
     * Getter for <code>sms.sms_user_passport.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    public Boolean getDeleted();

    /**
     * Setter for <code>sms.sms_user_passport.createDate</code>. 创建时间
     */
    public void setCreatedate(LocalDateTime value);

    /**
     * Getter for <code>sms.sms_user_passport.createDate</code>. 创建时间
     */
    public LocalDateTime getCreatedate();

    /**
     * Setter for <code>sms.sms_user_passport.createUser</code>. 创建人员
     */
    public void setCreateuser(String value);

    /**
     * Getter for <code>sms.sms_user_passport.createUser</code>. 创建人员
     */
    public String getCreateuser();

    /**
     * Setter for <code>sms.sms_user_passport.createOrg</code>. 创建机构
     */
    public void setCreateorg(String value);

    /**
     * Getter for <code>sms.sms_user_passport.createOrg</code>. 创建机构
     */
    public String getCreateorg();

    /**
     * Setter for <code>sms.sms_user_passport.updateDate</code>. 维护时间
     */
    public void setUpdatedate(LocalDateTime value);

    /**
     * Getter for <code>sms.sms_user_passport.updateDate</code>. 维护时间
     */
    public LocalDateTime getUpdatedate();

    /**
     * Setter for <code>sms.sms_user_passport.updateUser</code>. 维护人员
     */
    public void setUpdateuser(String value);

    /**
     * Getter for <code>sms.sms_user_passport.updateUser</code>. 维护人员
     */
    public String getUpdateuser();

    /**
     * Setter for <code>sms.sms_user_passport.updateOrg</code>. 维护机构
     */
    public void setUpdateorg(String value);

    /**
     * Getter for <code>sms.sms_user_passport.updateOrg</code>. 维护机构
     */
    public String getUpdateorg();

    /**
     * Setter for <code>sms.sms_user_passport.updateNo</code>. 维护序号
     */
    public void setUpdateno(Integer value);

    /**
     * Getter for <code>sms.sms_user_passport.updateNo</code>. 维护序号
     */
    public Integer getUpdateno();

    /**
     * Setter for <code>sms.sms_user_passport.entityId</code>. 所属实体
     */
    public void setEntityid(String value);

    /**
     * Getter for <code>sms.sms_user_passport.entityId</code>. 所属实体
     */
    public String getEntityid();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISmsUserPassport
     */
    public void from(ISmsUserPassport from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISmsUserPassport
     */
    public <E extends ISmsUserPassport> E into(E into);
}
