/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 权限-用户主表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISmsUserMast extends Serializable {

    /**
     * Setter for <code>sms.sms_user_mast.id</code>. 主键（用户编号）
     */
    public void setId(Long value);

    /**
     * Getter for <code>sms.sms_user_mast.id</code>. 主键（用户编号）
     */
    public Long getId();

    /**
     * Setter for <code>sms.sms_user_mast.name</code>. 用户名称
     */
    public void setName(String value);

    /**
     * Getter for <code>sms.sms_user_mast.name</code>. 用户名称
     */
    public String getName();

    /**
     * Setter for <code>sms.sms_user_mast.category</code>. 用户分类 1 user, 2 customer
     */
    public void setCategory(Integer value);

    /**
     * Getter for <code>sms.sms_user_mast.category</code>. 用户分类 1 user, 2 customer
     */
    public Integer getCategory();

    /**
     * Setter for <code>sms.sms_user_mast.customerId</code>. 用户客户编号
     */
    public void setCustomerid(String value);

    /**
     * Getter for <code>sms.sms_user_mast.customerId</code>. 用户客户编号
     */
    public String getCustomerid();

    /**
     * Setter for <code>sms.sms_user_mast.accountNo</code>. 商户虚拟账号
     */
    public void setAccountno(String value);

    /**
     * Getter for <code>sms.sms_user_mast.accountNo</code>. 商户虚拟账号
     */
    public String getAccountno();

    /**
     * Setter for <code>sms.sms_user_mast.mobile</code>. 用户手机号码
     */
    public void setMobile(String value);

    /**
     * Getter for <code>sms.sms_user_mast.mobile</code>. 用户手机号码
     */
    public String getMobile();

    /**
     * Setter for <code>sms.sms_user_mast.source</code>. 用户来源 added, invited, machine
     */
    public void setSource(String value);

    /**
     * Getter for <code>sms.sms_user_mast.source</code>. 用户来源 added, invited, machine
     */
    public String getSource();

    /**
     * Setter for <code>sms.sms_user_mast.pinCode</code>. 验证码
     */
    public void setPincode(String value);

    /**
     * Getter for <code>sms.sms_user_mast.pinCode</code>. 验证码
     */
    public String getPincode();

    /**
     * Setter for <code>sms.sms_user_mast.pinCodeDate</code>. 验证码时间
     */
    public void setPincodedate(LocalDateTime value);

    /**
     * Getter for <code>sms.sms_user_mast.pinCodeDate</code>. 验证码时间
     */
    public LocalDateTime getPincodedate();

    /**
     * Setter for <code>sms.sms_user_mast.status</code>. 状态 1 normal
     */
    public void setStatus(Integer value);

    /**
     * Getter for <code>sms.sms_user_mast.status</code>. 状态 1 normal
     */
    public Integer getStatus();

    /**
     * Setter for <code>sms.sms_user_mast.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    public void setDeleted(Boolean value);

    /**
     * Getter for <code>sms.sms_user_mast.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    public Boolean getDeleted();

    /**
     * Setter for <code>sms.sms_user_mast.createDate</code>. 创建时间
     */
    public void setCreatedate(LocalDateTime value);

    /**
     * Getter for <code>sms.sms_user_mast.createDate</code>. 创建时间
     */
    public LocalDateTime getCreatedate();

    /**
     * Setter for <code>sms.sms_user_mast.createUser</code>. 创建人员
     */
    public void setCreateuser(String value);

    /**
     * Getter for <code>sms.sms_user_mast.createUser</code>. 创建人员
     */
    public String getCreateuser();

    /**
     * Setter for <code>sms.sms_user_mast.createOrg</code>. 创建机构
     */
    public void setCreateorg(String value);

    /**
     * Getter for <code>sms.sms_user_mast.createOrg</code>. 创建机构
     */
    public String getCreateorg();

    /**
     * Setter for <code>sms.sms_user_mast.updateDate</code>. 维护时间
     */
    public void setUpdatedate(LocalDateTime value);

    /**
     * Getter for <code>sms.sms_user_mast.updateDate</code>. 维护时间
     */
    public LocalDateTime getUpdatedate();

    /**
     * Setter for <code>sms.sms_user_mast.updateUser</code>. 维护人员
     */
    public void setUpdateuser(String value);

    /**
     * Getter for <code>sms.sms_user_mast.updateUser</code>. 维护人员
     */
    public String getUpdateuser();

    /**
     * Setter for <code>sms.sms_user_mast.updateOrg</code>. 维护机构
     */
    public void setUpdateorg(String value);

    /**
     * Getter for <code>sms.sms_user_mast.updateOrg</code>. 维护机构
     */
    public String getUpdateorg();

    /**
     * Setter for <code>sms.sms_user_mast.updateNo</code>. 维护序号
     */
    public void setUpdateno(Integer value);

    /**
     * Getter for <code>sms.sms_user_mast.updateNo</code>. 维护序号
     */
    public Integer getUpdateno();

    /**
     * Setter for <code>sms.sms_user_mast.entityId</code>. 所属实体
     */
    public void setEntityid(String value);

    /**
     * Getter for <code>sms.sms_user_mast.entityId</code>. 所属实体
     */
    public String getEntityid();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISmsUserMast
     */
    public void from(ISmsUserMast from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISmsUserMast
     */
    public <E extends ISmsUserMast> E into(E into);
}
