/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 权限-用户分组主表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISmsGroupMast extends Serializable {

    /**
     * Setter for <code>sms.sms_group_mast.groupId</code>. 主键(用户组编号)
     */
    public void setGroupid(Long value);

    /**
     * Getter for <code>sms.sms_group_mast.groupId</code>. 主键(用户组编号)
     */
    public Long getGroupid();

    /**
     * Setter for <code>sms.sms_group_mast.name</code>. 用户组名称
     */
    public void setName(String value);

    /**
     * Getter for <code>sms.sms_group_mast.name</code>. 用户组名称
     */
    public String getName();

    /**
     * Setter for <code>sms.sms_group_mast.groupType</code>. 用户组类型 org/branch/dummy
     */
    public void setGrouptype(String value);

    /**
     * Getter for <code>sms.sms_group_mast.groupType</code>. 用户组类型 org/branch/dummy
     */
    public String getGrouptype();

    /**
     * Setter for <code>sms.sms_group_mast.treeLeaf</code>. 树形-是否叶子节点
     */
    public void setTreeleaf(String value);

    /**
     * Getter for <code>sms.sms_group_mast.treeLeaf</code>. 树形-是否叶子节点
     */
    public String getTreeleaf();

    /**
     * Setter for <code>sms.sms_group_mast.treeLevel</code>. 树形-级别
     */
    public void setTreelevel(Short value);

    /**
     * Getter for <code>sms.sms_group_mast.treeLevel</code>. 树形-级别
     */
    public Short getTreelevel();

    /**
     * Setter for <code>sms.sms_group_mast.treeParent</code>. 树形-父编号
     */
    public void setTreeparent(String value);

    /**
     * Getter for <code>sms.sms_group_mast.treeParent</code>. 树形-父编号
     */
    public String getTreeparent();

    /**
     * Setter for <code>sms.sms_group_mast.treeSequence</code>. 树形-排序
     */
    public void setTreesequence(String value);

    /**
     * Getter for <code>sms.sms_group_mast.treeSequence</code>. 树形-排序
     */
    public String getTreesequence();

    /**
     * Setter for <code>sms.sms_group_mast.adminId</code>. 管理员
     */
    public void setAdminid(String value);

    /**
     * Getter for <code>sms.sms_group_mast.adminId</code>. 管理员
     */
    public String getAdminid();

    /**
     * Setter for <code>sms.sms_group_mast.status</code>. 状态 1 normal
     */
    public void setStatus(Integer value);

    /**
     * Getter for <code>sms.sms_group_mast.status</code>. 状态 1 normal
     */
    public Integer getStatus();

    /**
     * Setter for <code>sms.sms_group_mast.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    public void setDeleted(Boolean value);

    /**
     * Getter for <code>sms.sms_group_mast.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    public Boolean getDeleted();

    /**
     * Setter for <code>sms.sms_group_mast.createDate</code>. 创建时间
     */
    public void setCreatedate(LocalDateTime value);

    /**
     * Getter for <code>sms.sms_group_mast.createDate</code>. 创建时间
     */
    public LocalDateTime getCreatedate();

    /**
     * Setter for <code>sms.sms_group_mast.createUser</code>. 创建人员
     */
    public void setCreateuser(String value);

    /**
     * Getter for <code>sms.sms_group_mast.createUser</code>. 创建人员
     */
    public String getCreateuser();

    /**
     * Setter for <code>sms.sms_group_mast.createOrg</code>. 创建机构
     */
    public void setCreateorg(String value);

    /**
     * Getter for <code>sms.sms_group_mast.createOrg</code>. 创建机构
     */
    public String getCreateorg();

    /**
     * Setter for <code>sms.sms_group_mast.updateDate</code>. 维护时间
     */
    public void setUpdatedate(LocalDateTime value);

    /**
     * Getter for <code>sms.sms_group_mast.updateDate</code>. 维护时间
     */
    public LocalDateTime getUpdatedate();

    /**
     * Setter for <code>sms.sms_group_mast.updateUser</code>. 维护人员
     */
    public void setUpdateuser(String value);

    /**
     * Getter for <code>sms.sms_group_mast.updateUser</code>. 维护人员
     */
    public String getUpdateuser();

    /**
     * Setter for <code>sms.sms_group_mast.updateOrg</code>. 维护机构
     */
    public void setUpdateorg(String value);

    /**
     * Getter for <code>sms.sms_group_mast.updateOrg</code>. 维护机构
     */
    public String getUpdateorg();

    /**
     * Setter for <code>sms.sms_group_mast.updateNo</code>. 维护序号
     */
    public void setUpdateno(Integer value);

    /**
     * Getter for <code>sms.sms_group_mast.updateNo</code>. 维护序号
     */
    public Integer getUpdateno();

    /**
     * Setter for <code>sms.sms_group_mast.entityId</code>. 所属实体
     */
    public void setEntityid(String value);

    /**
     * Getter for <code>sms.sms_group_mast.entityId</code>. 所属实体
     */
    public String getEntityid();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISmsGroupMast
     */
    public void from(ISmsGroupMast from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISmsGroupMast
     */
    public <E extends ISmsGroupMast> E into(E into);
}
