/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 权限-角色主表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISmsRoleMast extends Serializable {

    /**
     * Setter for <code>sms.sms_role_mast.id</code>. 主键-角色编号
     */
    public void setId(Long value);

    /**
     * Getter for <code>sms.sms_role_mast.id</code>. 主键-角色编号
     */
    public Long getId();

    /**
     * Setter for <code>sms.sms_role_mast.name</code>. 角色名称
     */
    public void setName(String value);

    /**
     * Getter for <code>sms.sms_role_mast.name</code>. 角色名称
     */
    public String getName();

    /**
     * Setter for <code>sms.sms_role_mast.adminFlag</code>. 是否管理员角色
     */
    public void setAdminflag(Integer value);

    /**
     * Getter for <code>sms.sms_role_mast.adminFlag</code>. 是否管理员角色
     */
    public Integer getAdminflag();

    /**
     * Setter for <code>sms.sms_role_mast.status</code>. 状态 1 normal
     */
    public void setStatus(Integer value);

    /**
     * Getter for <code>sms.sms_role_mast.status</code>. 状态 1 normal
     */
    public Integer getStatus();

    /**
     * Setter for <code>sms.sms_role_mast.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    public void setDeleted(Boolean value);

    /**
     * Getter for <code>sms.sms_role_mast.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    public Boolean getDeleted();

    /**
     * Setter for <code>sms.sms_role_mast.createDate</code>. 创建时间
     */
    public void setCreatedate(LocalDateTime value);

    /**
     * Getter for <code>sms.sms_role_mast.createDate</code>. 创建时间
     */
    public LocalDateTime getCreatedate();

    /**
     * Setter for <code>sms.sms_role_mast.createUser</code>. 创建人员
     */
    public void setCreateuser(String value);

    /**
     * Getter for <code>sms.sms_role_mast.createUser</code>. 创建人员
     */
    public String getCreateuser();

    /**
     * Setter for <code>sms.sms_role_mast.createOrg</code>. 创建机构
     */
    public void setCreateorg(String value);

    /**
     * Getter for <code>sms.sms_role_mast.createOrg</code>. 创建机构
     */
    public String getCreateorg();

    /**
     * Setter for <code>sms.sms_role_mast.updateDate</code>. 维护时间
     */
    public void setUpdatedate(LocalDateTime value);

    /**
     * Getter for <code>sms.sms_role_mast.updateDate</code>. 维护时间
     */
    public LocalDateTime getUpdatedate();

    /**
     * Setter for <code>sms.sms_role_mast.updateUser</code>. 维护人员
     */
    public void setUpdateuser(String value);

    /**
     * Getter for <code>sms.sms_role_mast.updateUser</code>. 维护人员
     */
    public String getUpdateuser();

    /**
     * Setter for <code>sms.sms_role_mast.updateOrg</code>. 维护机构
     */
    public void setUpdateorg(String value);

    /**
     * Getter for <code>sms.sms_role_mast.updateOrg</code>. 维护机构
     */
    public String getUpdateorg();

    /**
     * Setter for <code>sms.sms_role_mast.updateNo</code>. 维护序号
     */
    public void setUpdateno(Integer value);

    /**
     * Getter for <code>sms.sms_role_mast.updateNo</code>. 维护序号
     */
    public Integer getUpdateno();

    /**
     * Setter for <code>sms.sms_role_mast.entityId</code>. 所属实体
     */
    public void setEntityid(String value);

    /**
     * Getter for <code>sms.sms_role_mast.entityId</code>. 所属实体
     */
    public String getEntityid();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISmsRoleMast
     */
    public void from(ISmsRoleMast from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISmsRoleMast
     */
    public <E extends ISmsRoleMast> E into(E into);
}
