/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms.tables.daos;


import com.gvdroid.simple.jooq.code.sms.tables.SmsGroupRoleXref;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsGroupRoleXrefRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 权限-用户分组角色关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SmsGroupRoleXrefDao extends DAOImpl<SmsGroupRoleXrefRecord, com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref, Long> {

    /**
     * Create a new SmsGroupRoleXrefDao without any configuration
     */
    public SmsGroupRoleXrefDao() {
        super(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF, com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref.class);
    }

    /**
     * Create a new SmsGroupRoleXrefDao with an attached configuration
     */
    @Autowired
    public SmsGroupRoleXrefDao(Configuration configuration) {
        super(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF, com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref.class, configuration);
    }

    @Override
    public Long getId(com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchById(Long... values) {
        return fetch(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref fetchOneById(Long value) {
        return fetchOne(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.ID, value);
    }

    /**
     * Fetch records that have <code>groupId BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchRangeOfGroupid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.GROUPID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>groupId IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchByGroupid(Long... values) {
        return fetch(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.GROUPID, values);
    }

    /**
     * Fetch records that have <code>roleId BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchRangeOfRoleid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.ROLEID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>roleId IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchByRoleid(Long... values) {
        return fetch(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.ROLEID, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchRangeOfStatus(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchByStatus(Integer... values) {
        return fetch(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.STATUS, values);
    }

    /**
     * Fetch records that have <code>deleted BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchRangeOfDeleted(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.DELETED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>deleted IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchByDeleted(Boolean... values) {
        return fetch(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.DELETED, values);
    }

    /**
     * Fetch records that have <code>createDate BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchRangeOfCreatedate(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.CREATEDATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createDate IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchByCreatedate(LocalDateTime... values) {
        return fetch(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.CREATEDATE, values);
    }

    /**
     * Fetch records that have <code>createUser BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchRangeOfCreateuser(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.CREATEUSER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createUser IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchByCreateuser(String... values) {
        return fetch(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.CREATEUSER, values);
    }

    /**
     * Fetch records that have <code>createOrg BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchRangeOfCreateorg(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.CREATEORG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createOrg IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchByCreateorg(String... values) {
        return fetch(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.CREATEORG, values);
    }

    /**
     * Fetch records that have <code>updateDate BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchRangeOfUpdatedate(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.UPDATEDATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updateDate IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchByUpdatedate(LocalDateTime... values) {
        return fetch(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.UPDATEDATE, values);
    }

    /**
     * Fetch records that have <code>updateUser BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchRangeOfUpdateuser(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.UPDATEUSER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updateUser IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchByUpdateuser(String... values) {
        return fetch(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.UPDATEUSER, values);
    }

    /**
     * Fetch records that have <code>updateOrg BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchRangeOfUpdateorg(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.UPDATEORG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updateOrg IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchByUpdateorg(String... values) {
        return fetch(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.UPDATEORG, values);
    }

    /**
     * Fetch records that have <code>updateNo BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchRangeOfUpdateno(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.UPDATENO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updateNo IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchByUpdateno(Integer... values) {
        return fetch(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.UPDATENO, values);
    }

    /**
     * Fetch records that have <code>entityId BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchRangeOfEntityid(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.ENTITYID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>entityId IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupRoleXref> fetchByEntityid(String... values) {
        return fetch(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.ENTITYID, values);
    }
}
