/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms.tables.daos;


import com.gvdroid.simple.jooq.code.sms.tables.SmsGroupMast;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsGroupMastRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 权限-用户分组主表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SmsGroupMastDao extends DAOImpl<SmsGroupMastRecord, com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast, Long> {

    /**
     * Create a new SmsGroupMastDao without any configuration
     */
    public SmsGroupMastDao() {
        super(SmsGroupMast.SMS_GROUP_MAST, com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast.class);
    }

    /**
     * Create a new SmsGroupMastDao with an attached configuration
     */
    @Autowired
    public SmsGroupMastDao(Configuration configuration) {
        super(SmsGroupMast.SMS_GROUP_MAST, com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast.class, configuration);
    }

    @Override
    public Long getId(com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast object) {
        return object.getGroupid();
    }

    /**
     * Fetch records that have <code>groupId BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchRangeOfGroupid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SmsGroupMast.SMS_GROUP_MAST.GROUPID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>groupId IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchByGroupid(Long... values) {
        return fetch(SmsGroupMast.SMS_GROUP_MAST.GROUPID, values);
    }

    /**
     * Fetch a unique record that has <code>groupId = value</code>
     */
    public com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast fetchOneByGroupid(Long value) {
        return fetchOne(SmsGroupMast.SMS_GROUP_MAST.GROUPID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsGroupMast.SMS_GROUP_MAST.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchByName(String... values) {
        return fetch(SmsGroupMast.SMS_GROUP_MAST.NAME, values);
    }

    /**
     * Fetch records that have <code>groupType BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchRangeOfGrouptype(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsGroupMast.SMS_GROUP_MAST.GROUPTYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>groupType IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchByGrouptype(String... values) {
        return fetch(SmsGroupMast.SMS_GROUP_MAST.GROUPTYPE, values);
    }

    /**
     * Fetch records that have <code>treeLeaf BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchRangeOfTreeleaf(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsGroupMast.SMS_GROUP_MAST.TREELEAF, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>treeLeaf IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchByTreeleaf(String... values) {
        return fetch(SmsGroupMast.SMS_GROUP_MAST.TREELEAF, values);
    }

    /**
     * Fetch records that have <code>treeLevel BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchRangeOfTreelevel(Short lowerInclusive, Short upperInclusive) {
        return fetchRange(SmsGroupMast.SMS_GROUP_MAST.TREELEVEL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>treeLevel IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchByTreelevel(Short... values) {
        return fetch(SmsGroupMast.SMS_GROUP_MAST.TREELEVEL, values);
    }

    /**
     * Fetch records that have <code>treeParent BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchRangeOfTreeparent(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsGroupMast.SMS_GROUP_MAST.TREEPARENT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>treeParent IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchByTreeparent(String... values) {
        return fetch(SmsGroupMast.SMS_GROUP_MAST.TREEPARENT, values);
    }

    /**
     * Fetch records that have <code>treeSequence BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchRangeOfTreesequence(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsGroupMast.SMS_GROUP_MAST.TREESEQUENCE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>treeSequence IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchByTreesequence(String... values) {
        return fetch(SmsGroupMast.SMS_GROUP_MAST.TREESEQUENCE, values);
    }

    /**
     * Fetch records that have <code>adminId BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchRangeOfAdminid(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsGroupMast.SMS_GROUP_MAST.ADMINID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>adminId IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchByAdminid(String... values) {
        return fetch(SmsGroupMast.SMS_GROUP_MAST.ADMINID, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchRangeOfStatus(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(SmsGroupMast.SMS_GROUP_MAST.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchByStatus(Integer... values) {
        return fetch(SmsGroupMast.SMS_GROUP_MAST.STATUS, values);
    }

    /**
     * Fetch records that have <code>deleted BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchRangeOfDeleted(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(SmsGroupMast.SMS_GROUP_MAST.DELETED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>deleted IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchByDeleted(Boolean... values) {
        return fetch(SmsGroupMast.SMS_GROUP_MAST.DELETED, values);
    }

    /**
     * Fetch records that have <code>createDate BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchRangeOfCreatedate(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SmsGroupMast.SMS_GROUP_MAST.CREATEDATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createDate IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchByCreatedate(LocalDateTime... values) {
        return fetch(SmsGroupMast.SMS_GROUP_MAST.CREATEDATE, values);
    }

    /**
     * Fetch records that have <code>createUser BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchRangeOfCreateuser(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsGroupMast.SMS_GROUP_MAST.CREATEUSER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createUser IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchByCreateuser(String... values) {
        return fetch(SmsGroupMast.SMS_GROUP_MAST.CREATEUSER, values);
    }

    /**
     * Fetch records that have <code>createOrg BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchRangeOfCreateorg(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsGroupMast.SMS_GROUP_MAST.CREATEORG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createOrg IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchByCreateorg(String... values) {
        return fetch(SmsGroupMast.SMS_GROUP_MAST.CREATEORG, values);
    }

    /**
     * Fetch records that have <code>updateDate BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchRangeOfUpdatedate(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SmsGroupMast.SMS_GROUP_MAST.UPDATEDATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updateDate IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchByUpdatedate(LocalDateTime... values) {
        return fetch(SmsGroupMast.SMS_GROUP_MAST.UPDATEDATE, values);
    }

    /**
     * Fetch records that have <code>updateUser BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchRangeOfUpdateuser(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsGroupMast.SMS_GROUP_MAST.UPDATEUSER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updateUser IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchByUpdateuser(String... values) {
        return fetch(SmsGroupMast.SMS_GROUP_MAST.UPDATEUSER, values);
    }

    /**
     * Fetch records that have <code>updateOrg BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchRangeOfUpdateorg(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsGroupMast.SMS_GROUP_MAST.UPDATEORG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updateOrg IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchByUpdateorg(String... values) {
        return fetch(SmsGroupMast.SMS_GROUP_MAST.UPDATEORG, values);
    }

    /**
     * Fetch records that have <code>updateNo BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchRangeOfUpdateno(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(SmsGroupMast.SMS_GROUP_MAST.UPDATENO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updateNo IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchByUpdateno(Integer... values) {
        return fetch(SmsGroupMast.SMS_GROUP_MAST.UPDATENO, values);
    }

    /**
     * Fetch records that have <code>entityId BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchRangeOfEntityid(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsGroupMast.SMS_GROUP_MAST.ENTITYID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>entityId IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsGroupMast> fetchByEntityid(String... values) {
        return fetch(SmsGroupMast.SMS_GROUP_MAST.ENTITYID, values);
    }
}
