/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms.tables.daos;


import com.gvdroid.simple.jooq.code.sms.tables.SmsRoleResourceXref;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsRoleResourceXrefRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 权限-角色资源关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SmsRoleResourceXrefDao extends DAOImpl<SmsRoleResourceXrefRecord, com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref, Long> {

    /**
     * Create a new SmsRoleResourceXrefDao without any configuration
     */
    public SmsRoleResourceXrefDao() {
        super(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF, com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref.class);
    }

    /**
     * Create a new SmsRoleResourceXrefDao with an attached configuration
     */
    @Autowired
    public SmsRoleResourceXrefDao(Configuration configuration) {
        super(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF, com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref.class, configuration);
    }

    @Override
    public Long getId(com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchById(Long... values) {
        return fetch(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref fetchOneById(Long value) {
        return fetchOne(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.ID, value);
    }

    /**
     * Fetch records that have <code>roleId BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchRangeOfRoleid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.ROLEID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>roleId IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchByRoleid(Long... values) {
        return fetch(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.ROLEID, values);
    }

    /**
     * Fetch records that have <code>resourceId BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchRangeOfResourceid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.RESOURCEID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>resourceId IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchByResourceid(Long... values) {
        return fetch(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.RESOURCEID, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchRangeOfStatus(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchByStatus(Integer... values) {
        return fetch(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.STATUS, values);
    }

    /**
     * Fetch records that have <code>deleted BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchRangeOfDeleted(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.DELETED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>deleted IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchByDeleted(Boolean... values) {
        return fetch(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.DELETED, values);
    }

    /**
     * Fetch records that have <code>createDate BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchRangeOfCreatedate(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.CREATEDATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createDate IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchByCreatedate(LocalDateTime... values) {
        return fetch(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.CREATEDATE, values);
    }

    /**
     * Fetch records that have <code>createUser BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchRangeOfCreateuser(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.CREATEUSER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createUser IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchByCreateuser(String... values) {
        return fetch(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.CREATEUSER, values);
    }

    /**
     * Fetch records that have <code>createOrg BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchRangeOfCreateorg(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.CREATEORG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createOrg IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchByCreateorg(String... values) {
        return fetch(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.CREATEORG, values);
    }

    /**
     * Fetch records that have <code>updateDate BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchRangeOfUpdatedate(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.UPDATEDATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updateDate IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchByUpdatedate(LocalDateTime... values) {
        return fetch(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.UPDATEDATE, values);
    }

    /**
     * Fetch records that have <code>updateUser BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchRangeOfUpdateuser(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.UPDATEUSER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updateUser IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchByUpdateuser(String... values) {
        return fetch(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.UPDATEUSER, values);
    }

    /**
     * Fetch records that have <code>updateOrg BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchRangeOfUpdateorg(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.UPDATEORG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updateOrg IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchByUpdateorg(String... values) {
        return fetch(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.UPDATEORG, values);
    }

    /**
     * Fetch records that have <code>updateNo BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchRangeOfUpdateno(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.UPDATENO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updateNo IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchByUpdateno(Integer... values) {
        return fetch(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.UPDATENO, values);
    }

    /**
     * Fetch records that have <code>entity_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchRangeOfEntityId(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.ENTITY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>entity_id IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleResourceXref> fetchByEntityId(String... values) {
        return fetch(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.ENTITY_ID, values);
    }
}
