/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms.tables.daos;


import com.gvdroid.simple.jooq.code.sms.tables.SmsRoleMast;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsRoleMastRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 权限-角色主表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SmsRoleMastDao extends DAOImpl<SmsRoleMastRecord, com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast, Long> {

    /**
     * Create a new SmsRoleMastDao without any configuration
     */
    public SmsRoleMastDao() {
        super(SmsRoleMast.SMS_ROLE_MAST, com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast.class);
    }

    /**
     * Create a new SmsRoleMastDao with an attached configuration
     */
    @Autowired
    public SmsRoleMastDao(Configuration configuration) {
        super(SmsRoleMast.SMS_ROLE_MAST, com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast.class, configuration);
    }

    @Override
    public Long getId(com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SmsRoleMast.SMS_ROLE_MAST.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchById(Long... values) {
        return fetch(SmsRoleMast.SMS_ROLE_MAST.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast fetchOneById(Long value) {
        return fetchOne(SmsRoleMast.SMS_ROLE_MAST.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsRoleMast.SMS_ROLE_MAST.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchByName(String... values) {
        return fetch(SmsRoleMast.SMS_ROLE_MAST.NAME, values);
    }

    /**
     * Fetch records that have <code>adminFlag BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchRangeOfAdminflag(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(SmsRoleMast.SMS_ROLE_MAST.ADMINFLAG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>adminFlag IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchByAdminflag(Integer... values) {
        return fetch(SmsRoleMast.SMS_ROLE_MAST.ADMINFLAG, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchRangeOfStatus(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(SmsRoleMast.SMS_ROLE_MAST.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchByStatus(Integer... values) {
        return fetch(SmsRoleMast.SMS_ROLE_MAST.STATUS, values);
    }

    /**
     * Fetch records that have <code>deleted BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchRangeOfDeleted(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(SmsRoleMast.SMS_ROLE_MAST.DELETED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>deleted IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchByDeleted(Boolean... values) {
        return fetch(SmsRoleMast.SMS_ROLE_MAST.DELETED, values);
    }

    /**
     * Fetch records that have <code>createDate BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchRangeOfCreatedate(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SmsRoleMast.SMS_ROLE_MAST.CREATEDATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createDate IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchByCreatedate(LocalDateTime... values) {
        return fetch(SmsRoleMast.SMS_ROLE_MAST.CREATEDATE, values);
    }

    /**
     * Fetch records that have <code>createUser BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchRangeOfCreateuser(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsRoleMast.SMS_ROLE_MAST.CREATEUSER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createUser IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchByCreateuser(String... values) {
        return fetch(SmsRoleMast.SMS_ROLE_MAST.CREATEUSER, values);
    }

    /**
     * Fetch records that have <code>createOrg BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchRangeOfCreateorg(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsRoleMast.SMS_ROLE_MAST.CREATEORG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createOrg IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchByCreateorg(String... values) {
        return fetch(SmsRoleMast.SMS_ROLE_MAST.CREATEORG, values);
    }

    /**
     * Fetch records that have <code>updateDate BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchRangeOfUpdatedate(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SmsRoleMast.SMS_ROLE_MAST.UPDATEDATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updateDate IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchByUpdatedate(LocalDateTime... values) {
        return fetch(SmsRoleMast.SMS_ROLE_MAST.UPDATEDATE, values);
    }

    /**
     * Fetch records that have <code>updateUser BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchRangeOfUpdateuser(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsRoleMast.SMS_ROLE_MAST.UPDATEUSER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updateUser IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchByUpdateuser(String... values) {
        return fetch(SmsRoleMast.SMS_ROLE_MAST.UPDATEUSER, values);
    }

    /**
     * Fetch records that have <code>updateOrg BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchRangeOfUpdateorg(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsRoleMast.SMS_ROLE_MAST.UPDATEORG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updateOrg IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchByUpdateorg(String... values) {
        return fetch(SmsRoleMast.SMS_ROLE_MAST.UPDATEORG, values);
    }

    /**
     * Fetch records that have <code>updateNo BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchRangeOfUpdateno(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(SmsRoleMast.SMS_ROLE_MAST.UPDATENO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updateNo IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchByUpdateno(Integer... values) {
        return fetch(SmsRoleMast.SMS_ROLE_MAST.UPDATENO, values);
    }

    /**
     * Fetch records that have <code>entityId BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchRangeOfEntityid(String lowerInclusive, String upperInclusive) {
        return fetchRange(SmsRoleMast.SMS_ROLE_MAST.ENTITYID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>entityId IN (values)</code>
     */
    public List<com.gvdroid.simple.jooq.code.sms.tables.pojos.SmsRoleMast> fetchByEntityid(String... values) {
        return fetch(SmsRoleMast.SMS_ROLE_MAST.ENTITYID, values);
    }
}
