spring:
  application:
    name: gvdroid-simple-complex-server
  jackson:
    time-zone: GMT+8
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE_DATES_AS_TIMESTAMPS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  main:
    allow-bean-definition-overriding: true
  redis:
    url: "redis://@192.168.8.8:6379"
    database: 1
#    timeout: 5000
gd:
  list:
    - a
    - b
    - c
gvdroid:
  swagger:
    enabled: true
    base-package: com.gvdroid.simple.complex
    license: com.gvdroid.simple
    description: simple api
    title: simple api
    version: 0.0.1-SNAPSHOT
  business:
    logging:
      enabled: true
      env: dev #dev, prod
      method: mq # kafka
      category: 7 # 1=inquiry, 2=maintenance, 4=transaction
      mq:
        name: gvdroid.simple.logging
        queueDurable: true
        queueAutoDelete: false
        routing: gvdroid.simple.logging
        exchange: gvdroid.simple.logging
        exchangeDurable: true
        exchangeAutoDelete: false

logging:
  level:
    root: info
    com.gvdroid.simple.mybatis: debug

