/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms.tables;


import com.gvdroid.simple.jooq.code.sms.Keys;
import com.gvdroid.simple.jooq.code.sms.Sms;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsRoleMastRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 权限-角色主表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SmsRoleMast extends TableImpl<SmsRoleMastRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sms.sms_role_mast</code>
     */
    public static final SmsRoleMast SMS_ROLE_MAST = new SmsRoleMast();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SmsRoleMastRecord> getRecordType() {
        return SmsRoleMastRecord.class;
    }

    /**
     * The column <code>sms.sms_role_mast.id</code>. 主键-角色编号
     */
    public final TableField<SmsRoleMastRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "主键-角色编号");

    /**
     * The column <code>sms.sms_role_mast.name</code>. 角色名称
     */
    public final TableField<SmsRoleMastRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(128).nullable(false), this, "角色名称");

    /**
     * The column <code>sms.sms_role_mast.adminFlag</code>. 是否管理员角色
     */
    public final TableField<SmsRoleMastRecord, Integer> ADMINFLAG = createField(DSL.name("adminFlag"), SQLDataType.INTEGER.nullable(false), this, "是否管理员角色");

    /**
     * The column <code>sms.sms_role_mast.status</code>. 状态 1 normal
     */
    public final TableField<SmsRoleMastRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this, "状态 1 normal");

    /**
     * The column <code>sms.sms_role_mast.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    public final TableField<SmsRoleMastRecord, Boolean> DELETED = createField(DSL.name("deleted"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'0'", SQLDataType.BIT)), this, "删除状态 0 正常 1 逻辑删除");

    /**
     * The column <code>sms.sms_role_mast.createDate</code>. 创建时间
     */
    public final TableField<SmsRoleMastRecord, LocalDateTime> CREATEDATE = createField(DSL.name("createDate"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>sms.sms_role_mast.createUser</code>. 创建人员
     */
    public final TableField<SmsRoleMastRecord, String> CREATEUSER = createField(DSL.name("createUser"), SQLDataType.VARCHAR(32).nullable(false), this, "创建人员");

    /**
     * The column <code>sms.sms_role_mast.createOrg</code>. 创建机构
     */
    public final TableField<SmsRoleMastRecord, String> CREATEORG = createField(DSL.name("createOrg"), SQLDataType.VARCHAR(32).nullable(false), this, "创建机构");

    /**
     * The column <code>sms.sms_role_mast.updateDate</code>. 维护时间
     */
    public final TableField<SmsRoleMastRecord, LocalDateTime> UPDATEDATE = createField(DSL.name("updateDate"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "维护时间");

    /**
     * The column <code>sms.sms_role_mast.updateUser</code>. 维护人员
     */
    public final TableField<SmsRoleMastRecord, String> UPDATEUSER = createField(DSL.name("updateUser"), SQLDataType.VARCHAR(32).nullable(false), this, "维护人员");

    /**
     * The column <code>sms.sms_role_mast.updateOrg</code>. 维护机构
     */
    public final TableField<SmsRoleMastRecord, String> UPDATEORG = createField(DSL.name("updateOrg"), SQLDataType.VARCHAR(32).nullable(false), this, "维护机构");

    /**
     * The column <code>sms.sms_role_mast.updateNo</code>. 维护序号
     */
    public final TableField<SmsRoleMastRecord, Integer> UPDATENO = createField(DSL.name("updateNo"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "维护序号");

    /**
     * The column <code>sms.sms_role_mast.entityId</code>. 所属实体
     */
    public final TableField<SmsRoleMastRecord, String> ENTITYID = createField(DSL.name("entityId"), SQLDataType.VARCHAR(32).nullable(false), this, "所属实体");

    private SmsRoleMast(Name alias, Table<SmsRoleMastRecord> aliased) {
        this(alias, aliased, null);
    }

    private SmsRoleMast(Name alias, Table<SmsRoleMastRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("权限-角色主表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>sms.sms_role_mast</code> table reference
     */
    public SmsRoleMast(String alias) {
        this(DSL.name(alias), SMS_ROLE_MAST);
    }

    /**
     * Create an aliased <code>sms.sms_role_mast</code> table reference
     */
    public SmsRoleMast(Name alias) {
        this(alias, SMS_ROLE_MAST);
    }

    /**
     * Create a <code>sms.sms_role_mast</code> table reference
     */
    public SmsRoleMast() {
        this(DSL.name("sms_role_mast"), null);
    }

    public <O extends Record> SmsRoleMast(Table<O> child, ForeignKey<O, SmsRoleMastRecord> key) {
        super(child, key, SMS_ROLE_MAST);
    }

    @Override
    public Schema getSchema() {
        return Sms.SMS;
    }

    @Override
    public UniqueKey<SmsRoleMastRecord> getPrimaryKey() {
        return Keys.KEY_SMS_ROLE_MAST_PRIMARY;
    }

    @Override
    public List<UniqueKey<SmsRoleMastRecord>> getKeys() {
        return Arrays.<UniqueKey<SmsRoleMastRecord>>asList(Keys.KEY_SMS_ROLE_MAST_PRIMARY, Keys.KEY_SMS_ROLE_MAST_IN_SMS_ROLE_MAST_1);
    }

    @Override
    public SmsRoleMast as(String alias) {
        return new SmsRoleMast(DSL.name(alias), this);
    }

    @Override
    public SmsRoleMast as(Name alias) {
        return new SmsRoleMast(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SmsRoleMast rename(String name) {
        return new SmsRoleMast(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SmsRoleMast rename(Name name) {
        return new SmsRoleMast(name, null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, Integer, Integer, Boolean, LocalDateTime, String, String, LocalDateTime, String, String, Integer, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }
}
