/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms.tables;


import com.gvdroid.simple.jooq.code.sms.Keys;
import com.gvdroid.simple.jooq.code.sms.Sms;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsRoleResourceXrefRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 权限-角色资源关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SmsRoleResourceXref extends TableImpl<SmsRoleResourceXrefRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sms.sms_role_resource_xref</code>
     */
    public static final SmsRoleResourceXref SMS_ROLE_RESOURCE_XREF = new SmsRoleResourceXref();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SmsRoleResourceXrefRecord> getRecordType() {
        return SmsRoleResourceXrefRecord.class;
    }

    /**
     * The column <code>sms.sms_role_resource_xref.id</code>. 主键
     */
    public final TableField<SmsRoleResourceXrefRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "主键");

    /**
     * The column <code>sms.sms_role_resource_xref.roleId</code>. 角色编号
     */
    public final TableField<SmsRoleResourceXrefRecord, Long> ROLEID = createField(DSL.name("roleId"), SQLDataType.BIGINT.nullable(false), this, "角色编号");

    /**
     * The column <code>sms.sms_role_resource_xref.resourceId</code>. 资源编号
     */
    public final TableField<SmsRoleResourceXrefRecord, Long> RESOURCEID = createField(DSL.name("resourceId"), SQLDataType.BIGINT.nullable(false), this, "资源编号");

    /**
     * The column <code>sms.sms_role_resource_xref.status</code>. 状态 1 normal
     */
    public final TableField<SmsRoleResourceXrefRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this, "状态 1 normal");

    /**
     * The column <code>sms.sms_role_resource_xref.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    public final TableField<SmsRoleResourceXrefRecord, Boolean> DELETED = createField(DSL.name("deleted"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'0'", SQLDataType.BIT)), this, "删除状态 0 正常 1 逻辑删除");

    /**
     * The column <code>sms.sms_role_resource_xref.createDate</code>. 创建时间
     */
    public final TableField<SmsRoleResourceXrefRecord, LocalDateTime> CREATEDATE = createField(DSL.name("createDate"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>sms.sms_role_resource_xref.createUser</code>. 创建人员
     */
    public final TableField<SmsRoleResourceXrefRecord, String> CREATEUSER = createField(DSL.name("createUser"), SQLDataType.VARCHAR(32).nullable(false), this, "创建人员");

    /**
     * The column <code>sms.sms_role_resource_xref.createOrg</code>. 创建机构
     */
    public final TableField<SmsRoleResourceXrefRecord, String> CREATEORG = createField(DSL.name("createOrg"), SQLDataType.VARCHAR(32).nullable(false), this, "创建机构");

    /**
     * The column <code>sms.sms_role_resource_xref.updateDate</code>. 维护时间
     */
    public final TableField<SmsRoleResourceXrefRecord, LocalDateTime> UPDATEDATE = createField(DSL.name("updateDate"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "维护时间");

    /**
     * The column <code>sms.sms_role_resource_xref.updateUser</code>. 维护人员
     */
    public final TableField<SmsRoleResourceXrefRecord, String> UPDATEUSER = createField(DSL.name("updateUser"), SQLDataType.VARCHAR(32).nullable(false), this, "维护人员");

    /**
     * The column <code>sms.sms_role_resource_xref.updateOrg</code>. 维护机构
     */
    public final TableField<SmsRoleResourceXrefRecord, String> UPDATEORG = createField(DSL.name("updateOrg"), SQLDataType.VARCHAR(32).nullable(false), this, "维护机构");

    /**
     * The column <code>sms.sms_role_resource_xref.updateNo</code>. 维护序号
     */
    public final TableField<SmsRoleResourceXrefRecord, Integer> UPDATENO = createField(DSL.name("updateNo"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "维护序号");

    /**
     * The column <code>sms.sms_role_resource_xref.entity_id</code>. 所属实体
     */
    public final TableField<SmsRoleResourceXrefRecord, String> ENTITY_ID = createField(DSL.name("entity_id"), SQLDataType.VARCHAR(32).nullable(false), this, "所属实体");

    private SmsRoleResourceXref(Name alias, Table<SmsRoleResourceXrefRecord> aliased) {
        this(alias, aliased, null);
    }

    private SmsRoleResourceXref(Name alias, Table<SmsRoleResourceXrefRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("权限-角色资源关联表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>sms.sms_role_resource_xref</code> table reference
     */
    public SmsRoleResourceXref(String alias) {
        this(DSL.name(alias), SMS_ROLE_RESOURCE_XREF);
    }

    /**
     * Create an aliased <code>sms.sms_role_resource_xref</code> table reference
     */
    public SmsRoleResourceXref(Name alias) {
        this(alias, SMS_ROLE_RESOURCE_XREF);
    }

    /**
     * Create a <code>sms.sms_role_resource_xref</code> table reference
     */
    public SmsRoleResourceXref() {
        this(DSL.name("sms_role_resource_xref"), null);
    }

    public <O extends Record> SmsRoleResourceXref(Table<O> child, ForeignKey<O, SmsRoleResourceXrefRecord> key) {
        super(child, key, SMS_ROLE_RESOURCE_XREF);
    }

    @Override
    public Schema getSchema() {
        return Sms.SMS;
    }

    @Override
    public UniqueKey<SmsRoleResourceXrefRecord> getPrimaryKey() {
        return Keys.KEY_SMS_ROLE_RESOURCE_XREF_PRIMARY;
    }

    @Override
    public List<UniqueKey<SmsRoleResourceXrefRecord>> getKeys() {
        return Arrays.<UniqueKey<SmsRoleResourceXrefRecord>>asList(Keys.KEY_SMS_ROLE_RESOURCE_XREF_PRIMARY, Keys.KEY_SMS_ROLE_RESOURCE_XREF_IN_SMS_ROLE_FUNCTION_XREF_1);
    }

    @Override
    public SmsRoleResourceXref as(String alias) {
        return new SmsRoleResourceXref(DSL.name(alias), this);
    }

    @Override
    public SmsRoleResourceXref as(Name alias) {
        return new SmsRoleResourceXref(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SmsRoleResourceXref rename(String name) {
        return new SmsRoleResourceXref(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SmsRoleResourceXref rename(Name name) {
        return new SmsRoleResourceXref(name, null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, Long, Long, Integer, Boolean, LocalDateTime, String, String, LocalDateTime, String, String, Integer, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }
}
