/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms.tables;


import com.gvdroid.simple.jooq.code.sms.Keys;
import com.gvdroid.simple.jooq.code.sms.Sms;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsResourceMastRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row18;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 权限-权限主表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SmsResourceMast extends TableImpl<SmsResourceMastRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sms.sms_resource_mast</code>
     */
    public static final SmsResourceMast SMS_RESOURCE_MAST = new SmsResourceMast();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SmsResourceMastRecord> getRecordType() {
        return SmsResourceMastRecord.class;
    }

    /**
     * The column <code>sms.sms_resource_mast.id</code>. 功能编号
     */
    public final TableField<SmsResourceMastRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "功能编号");

    /**
     * The column <code>sms.sms_resource_mast.name</code>. 功能名称
     */
    public final TableField<SmsResourceMastRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(128).nullable(false), this, "功能名称");

    /**
     * The column <code>sms.sms_resource_mast.resourceType</code>. 功能类型 interface/page/element/data
     */
    public final TableField<SmsResourceMastRecord, String> RESOURCETYPE = createField(DSL.name("resourceType"), SQLDataType.VARCHAR(16).nullable(false), this, "功能类型 interface/page/element/data");

    /**
     * The column <code>sms.sms_resource_mast.resources</code>. 功能资源 如按钮id 页面url
     */
    public final TableField<SmsResourceMastRecord, String> RESOURCES = createField(DSL.name("resources"), SQLDataType.VARCHAR(256).nullable(false), this, "功能资源 如按钮id 页面url");

    /**
     * The column <code>sms.sms_resource_mast.treeLeaf</code>. 树形-是否叶子节点
     */
    public final TableField<SmsResourceMastRecord, Boolean> TREELEAF = createField(DSL.name("treeLeaf"), SQLDataType.BIT.nullable(false), this, "树形-是否叶子节点");

    /**
     * The column <code>sms.sms_resource_mast.treeLevel</code>. 树形-级别
     */
    public final TableField<SmsResourceMastRecord, Short> TREELEVEL = createField(DSL.name("treeLevel"), SQLDataType.SMALLINT.nullable(false), this, "树形-级别");

    /**
     * The column <code>sms.sms_resource_mast.treeParent</code>. 树形-父编号
     */
    public final TableField<SmsResourceMastRecord, String> TREEPARENT = createField(DSL.name("treeParent"), SQLDataType.VARCHAR(32).nullable(false), this, "树形-父编号");

    /**
     * The column <code>sms.sms_resource_mast.treeSequence</code>. 树形-排序
     */
    public final TableField<SmsResourceMastRecord, String> TREESEQUENCE = createField(DSL.name("treeSequence"), SQLDataType.VARCHAR(512).nullable(false), this, "树形-排序");

    /**
     * The column <code>sms.sms_resource_mast.status</code>. 状态 1 normal
     */
    public final TableField<SmsResourceMastRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this, "状态 1 normal");

    /**
     * The column <code>sms.sms_resource_mast.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    public final TableField<SmsResourceMastRecord, Boolean> DELETED = createField(DSL.name("deleted"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'0'", SQLDataType.BIT)), this, "删除状态 0 正常 1 逻辑删除");

    /**
     * The column <code>sms.sms_resource_mast.createDate</code>. 创建时间
     */
    public final TableField<SmsResourceMastRecord, LocalDateTime> CREATEDATE = createField(DSL.name("createDate"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>sms.sms_resource_mast.createUser</code>. 创建人员
     */
    public final TableField<SmsResourceMastRecord, String> CREATEUSER = createField(DSL.name("createUser"), SQLDataType.VARCHAR(32).nullable(false), this, "创建人员");

    /**
     * The column <code>sms.sms_resource_mast.createOrg</code>. 创建机构
     */
    public final TableField<SmsResourceMastRecord, String> CREATEORG = createField(DSL.name("createOrg"), SQLDataType.VARCHAR(32).nullable(false), this, "创建机构");

    /**
     * The column <code>sms.sms_resource_mast.updateDate</code>. 维护时间
     */
    public final TableField<SmsResourceMastRecord, LocalDateTime> UPDATEDATE = createField(DSL.name("updateDate"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "维护时间");

    /**
     * The column <code>sms.sms_resource_mast.updateUser</code>. 维护人员
     */
    public final TableField<SmsResourceMastRecord, String> UPDATEUSER = createField(DSL.name("updateUser"), SQLDataType.VARCHAR(32).nullable(false), this, "维护人员");

    /**
     * The column <code>sms.sms_resource_mast.updateOrg</code>. 维护机构
     */
    public final TableField<SmsResourceMastRecord, String> UPDATEORG = createField(DSL.name("updateOrg"), SQLDataType.VARCHAR(32).nullable(false), this, "维护机构");

    /**
     * The column <code>sms.sms_resource_mast.updateNo</code>. 维护序号
     */
    public final TableField<SmsResourceMastRecord, Integer> UPDATENO = createField(DSL.name("updateNo"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "维护序号");

    /**
     * The column <code>sms.sms_resource_mast.entityId</code>. 所属实体
     */
    public final TableField<SmsResourceMastRecord, String> ENTITYID = createField(DSL.name("entityId"), SQLDataType.VARCHAR(32).nullable(false), this, "所属实体");

    private SmsResourceMast(Name alias, Table<SmsResourceMastRecord> aliased) {
        this(alias, aliased, null);
    }

    private SmsResourceMast(Name alias, Table<SmsResourceMastRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("权限-权限主表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>sms.sms_resource_mast</code> table reference
     */
    public SmsResourceMast(String alias) {
        this(DSL.name(alias), SMS_RESOURCE_MAST);
    }

    /**
     * Create an aliased <code>sms.sms_resource_mast</code> table reference
     */
    public SmsResourceMast(Name alias) {
        this(alias, SMS_RESOURCE_MAST);
    }

    /**
     * Create a <code>sms.sms_resource_mast</code> table reference
     */
    public SmsResourceMast() {
        this(DSL.name("sms_resource_mast"), null);
    }

    public <O extends Record> SmsResourceMast(Table<O> child, ForeignKey<O, SmsResourceMastRecord> key) {
        super(child, key, SMS_RESOURCE_MAST);
    }

    @Override
    public Schema getSchema() {
        return Sms.SMS;
    }

    @Override
    public UniqueKey<SmsResourceMastRecord> getPrimaryKey() {
        return Keys.KEY_SMS_RESOURCE_MAST_PRIMARY;
    }

    @Override
    public List<UniqueKey<SmsResourceMastRecord>> getKeys() {
        return Arrays.<UniqueKey<SmsResourceMastRecord>>asList(Keys.KEY_SMS_RESOURCE_MAST_PRIMARY, Keys.KEY_SMS_RESOURCE_MAST_IN_SMS_FUNCTION_MAST_1);
    }

    @Override
    public SmsResourceMast as(String alias) {
        return new SmsResourceMast(DSL.name(alias), this);
    }

    @Override
    public SmsResourceMast as(Name alias) {
        return new SmsResourceMast(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SmsResourceMast rename(String name) {
        return new SmsResourceMast(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SmsResourceMast rename(Name name) {
        return new SmsResourceMast(name, null);
    }

    // -------------------------------------------------------------------------
    // Row18 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row18<Long, String, String, String, Boolean, Short, String, String, Integer, Boolean, LocalDateTime, String, String, LocalDateTime, String, String, Integer, String> fieldsRow() {
        return (Row18) super.fieldsRow();
    }
}
