/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms.tables;


import com.gvdroid.simple.jooq.code.sms.Indexes;
import com.gvdroid.simple.jooq.code.sms.Keys;
import com.gvdroid.simple.jooq.code.sms.Sms;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsUserPassportRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row17;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 权限-用户登陆凭证
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SmsUserPassport extends TableImpl<SmsUserPassportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sms.sms_user_passport</code>
     */
    public static final SmsUserPassport SMS_USER_PASSPORT = new SmsUserPassport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SmsUserPassportRecord> getRecordType() {
        return SmsUserPassportRecord.class;
    }

    /**
     * The column <code>sms.sms_user_passport.id</code>. 主键
     */
    public final TableField<SmsUserPassportRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "主键");

    /**
     * The column <code>sms.sms_user_passport.userId</code>. 用户编号
     */
    public final TableField<SmsUserPassportRecord, Long> USERID = createField(DSL.name("userId"), SQLDataType.BIGINT.nullable(false), this, "用户编号");

    /**
     * The column <code>sms.sms_user_passport.passportType</code>. 账号类型 account, weixin, qq, weibo, jd, github
     */
    public final TableField<SmsUserPassportRecord, String> PASSPORTTYPE = createField(DSL.name("passportType"), SQLDataType.VARCHAR(32).nullable(false), this, "账号类型 account, weixin, qq, weibo, jd, github");

    /**
     * The column <code>sms.sms_user_passport.passportNo</code>. 登录账号
     */
    public final TableField<SmsUserPassportRecord, String> PASSPORTNO = createField(DSL.name("passportNo"), SQLDataType.VARCHAR(128).nullable(false), this, "登录账号");

    /**
     * The column <code>sms.sms_user_passport.saltCode</code>. 混淆码
     */
    public final TableField<SmsUserPassportRecord, String> SALTCODE = createField(DSL.name("saltCode"), SQLDataType.VARCHAR(32), this, "混淆码");

    /**
     * The column <code>sms.sms_user_passport.password</code>. 登录密码
     */
    public final TableField<SmsUserPassportRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(128), this, "登录密码");

    /**
     * The column <code>sms.sms_user_passport.lastLoginDate</code>. 上次登录时间
     */
    public final TableField<SmsUserPassportRecord, LocalDateTime> LASTLOGINDATE = createField(DSL.name("lastLoginDate"), SQLDataType.LOCALDATETIME(0), this, "上次登录时间");

    /**
     * The column <code>sms.sms_user_passport.status</code>. 状态 1 normal
     */
    public final TableField<SmsUserPassportRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this, "状态 1 normal");

    /**
     * The column <code>sms.sms_user_passport.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    public final TableField<SmsUserPassportRecord, Boolean> DELETED = createField(DSL.name("deleted"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'0'", SQLDataType.BIT)), this, "删除状态 0 正常 1 逻辑删除");

    /**
     * The column <code>sms.sms_user_passport.createDate</code>. 创建时间
     */
    public final TableField<SmsUserPassportRecord, LocalDateTime> CREATEDATE = createField(DSL.name("createDate"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>sms.sms_user_passport.createUser</code>. 创建人员
     */
    public final TableField<SmsUserPassportRecord, String> CREATEUSER = createField(DSL.name("createUser"), SQLDataType.VARCHAR(32).nullable(false), this, "创建人员");

    /**
     * The column <code>sms.sms_user_passport.createOrg</code>. 创建机构
     */
    public final TableField<SmsUserPassportRecord, String> CREATEORG = createField(DSL.name("createOrg"), SQLDataType.VARCHAR(32).nullable(false), this, "创建机构");

    /**
     * The column <code>sms.sms_user_passport.updateDate</code>. 维护时间
     */
    public final TableField<SmsUserPassportRecord, LocalDateTime> UPDATEDATE = createField(DSL.name("updateDate"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "维护时间");

    /**
     * The column <code>sms.sms_user_passport.updateUser</code>. 维护人员
     */
    public final TableField<SmsUserPassportRecord, String> UPDATEUSER = createField(DSL.name("updateUser"), SQLDataType.VARCHAR(32).nullable(false), this, "维护人员");

    /**
     * The column <code>sms.sms_user_passport.updateOrg</code>. 维护机构
     */
    public final TableField<SmsUserPassportRecord, String> UPDATEORG = createField(DSL.name("updateOrg"), SQLDataType.VARCHAR(32).nullable(false), this, "维护机构");

    /**
     * The column <code>sms.sms_user_passport.updateNo</code>. 维护序号
     */
    public final TableField<SmsUserPassportRecord, Integer> UPDATENO = createField(DSL.name("updateNo"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "维护序号");

    /**
     * The column <code>sms.sms_user_passport.entityId</code>. 所属实体
     */
    public final TableField<SmsUserPassportRecord, String> ENTITYID = createField(DSL.name("entityId"), SQLDataType.VARCHAR(32).nullable(false), this, "所属实体");

    private SmsUserPassport(Name alias, Table<SmsUserPassportRecord> aliased) {
        this(alias, aliased, null);
    }

    private SmsUserPassport(Name alias, Table<SmsUserPassportRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("权限-用户登陆凭证"), TableOptions.table());
    }

    /**
     * Create an aliased <code>sms.sms_user_passport</code> table reference
     */
    public SmsUserPassport(String alias) {
        this(DSL.name(alias), SMS_USER_PASSPORT);
    }

    /**
     * Create an aliased <code>sms.sms_user_passport</code> table reference
     */
    public SmsUserPassport(Name alias) {
        this(alias, SMS_USER_PASSPORT);
    }

    /**
     * Create a <code>sms.sms_user_passport</code> table reference
     */
    public SmsUserPassport() {
        this(DSL.name("sms_user_passport"), null);
    }

    public <O extends Record> SmsUserPassport(Table<O> child, ForeignKey<O, SmsUserPassportRecord> key) {
        super(child, key, SMS_USER_PASSPORT);
    }

    @Override
    public Schema getSchema() {
        return Sms.SMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SMS_USER_PASSPORT_IN_SMS_USER_PASSPORT_2);
    }

    @Override
    public UniqueKey<SmsUserPassportRecord> getPrimaryKey() {
        return Keys.KEY_SMS_USER_PASSPORT_PRIMARY;
    }

    @Override
    public List<UniqueKey<SmsUserPassportRecord>> getKeys() {
        return Arrays.<UniqueKey<SmsUserPassportRecord>>asList(Keys.KEY_SMS_USER_PASSPORT_PRIMARY, Keys.KEY_SMS_USER_PASSPORT_IN_SMS_USER_PASSPORT_1);
    }

    @Override
    public SmsUserPassport as(String alias) {
        return new SmsUserPassport(DSL.name(alias), this);
    }

    @Override
    public SmsUserPassport as(Name alias) {
        return new SmsUserPassport(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SmsUserPassport rename(String name) {
        return new SmsUserPassport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SmsUserPassport rename(Name name) {
        return new SmsUserPassport(name, null);
    }

    // -------------------------------------------------------------------------
    // Row17 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row17<Long, Long, String, String, String, String, LocalDateTime, Integer, Boolean, LocalDateTime, String, String, LocalDateTime, String, String, Integer, String> fieldsRow() {
        return (Row17) super.fieldsRow();
    }
}
