/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms.tables;


import com.gvdroid.simple.jooq.code.sms.Keys;
import com.gvdroid.simple.jooq.code.sms.Sms;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsUserEventMastRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row15;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 权限-用户事件主表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SmsUserEventMast extends TableImpl<SmsUserEventMastRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sms.sms_user_event_mast</code>
     */
    public static final SmsUserEventMast SMS_USER_EVENT_MAST = new SmsUserEventMast();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SmsUserEventMastRecord> getRecordType() {
        return SmsUserEventMastRecord.class;
    }

    /**
     * The column <code>sms.sms_user_event_mast.id</code>. 主键
     */
    public final TableField<SmsUserEventMastRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "主键");

    /**
     * The column <code>sms.sms_user_event_mast.userId</code>. 用户编号
     */
    public final TableField<SmsUserEventMastRecord, Long> USERID = createField(DSL.name("userId"), SQLDataType.BIGINT.nullable(false), this, "用户编号");

    /**
     * The column <code>sms.sms_user_event_mast.eventType</code>. 事件类型 signup, signoff, signin, signout, binding, unbinding, locked, unlock
     */
    public final TableField<SmsUserEventMastRecord, String> EVENTTYPE = createField(DSL.name("eventType"), SQLDataType.VARCHAR(16).nullable(false), this, "事件类型 signup, signoff, signin, signout, binding, unbinding, locked, unlock");

    /**
     * The column <code>sms.sms_user_event_mast.content</code>. 事件对象
     */
    public final TableField<SmsUserEventMastRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB, this, "事件对象");

    /**
     * The column <code>sms.sms_user_event_mast.memo</code>. 事件描述
     */
    public final TableField<SmsUserEventMastRecord, String> MEMO = createField(DSL.name("memo"), SQLDataType.VARCHAR(64).nullable(false), this, "事件描述");

    /**
     * The column <code>sms.sms_user_event_mast.status</code>. 状态 1 normal
     */
    public final TableField<SmsUserEventMastRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this, "状态 1 normal");

    /**
     * The column <code>sms.sms_user_event_mast.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    public final TableField<SmsUserEventMastRecord, Boolean> DELETED = createField(DSL.name("deleted"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'0'", SQLDataType.BIT)), this, "删除状态 0 正常 1 逻辑删除");

    /**
     * The column <code>sms.sms_user_event_mast.createDate</code>. 创建时间
     */
    public final TableField<SmsUserEventMastRecord, LocalDateTime> CREATEDATE = createField(DSL.name("createDate"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>sms.sms_user_event_mast.createUser</code>. 创建人员
     */
    public final TableField<SmsUserEventMastRecord, String> CREATEUSER = createField(DSL.name("createUser"), SQLDataType.VARCHAR(32).nullable(false), this, "创建人员");

    /**
     * The column <code>sms.sms_user_event_mast.createOrg</code>. 创建机构
     */
    public final TableField<SmsUserEventMastRecord, String> CREATEORG = createField(DSL.name("createOrg"), SQLDataType.VARCHAR(32).nullable(false), this, "创建机构");

    /**
     * The column <code>sms.sms_user_event_mast.updateDate</code>. 维护时间
     */
    public final TableField<SmsUserEventMastRecord, LocalDateTime> UPDATEDATE = createField(DSL.name("updateDate"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "维护时间");

    /**
     * The column <code>sms.sms_user_event_mast.updateUser</code>. 维护人员
     */
    public final TableField<SmsUserEventMastRecord, String> UPDATEUSER = createField(DSL.name("updateUser"), SQLDataType.VARCHAR(32).nullable(false), this, "维护人员");

    /**
     * The column <code>sms.sms_user_event_mast.updateOrg</code>. 维护机构
     */
    public final TableField<SmsUserEventMastRecord, String> UPDATEORG = createField(DSL.name("updateOrg"), SQLDataType.VARCHAR(32).nullable(false), this, "维护机构");

    /**
     * The column <code>sms.sms_user_event_mast.updateNo</code>. 维护序号
     */
    public final TableField<SmsUserEventMastRecord, Integer> UPDATENO = createField(DSL.name("updateNo"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "维护序号");

    /**
     * The column <code>sms.sms_user_event_mast.entityId</code>. 所属实体
     */
    public final TableField<SmsUserEventMastRecord, String> ENTITYID = createField(DSL.name("entityId"), SQLDataType.VARCHAR(32).nullable(false), this, "所属实体");

    private SmsUserEventMast(Name alias, Table<SmsUserEventMastRecord> aliased) {
        this(alias, aliased, null);
    }

    private SmsUserEventMast(Name alias, Table<SmsUserEventMastRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("权限-用户事件主表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>sms.sms_user_event_mast</code> table reference
     */
    public SmsUserEventMast(String alias) {
        this(DSL.name(alias), SMS_USER_EVENT_MAST);
    }

    /**
     * Create an aliased <code>sms.sms_user_event_mast</code> table reference
     */
    public SmsUserEventMast(Name alias) {
        this(alias, SMS_USER_EVENT_MAST);
    }

    /**
     * Create a <code>sms.sms_user_event_mast</code> table reference
     */
    public SmsUserEventMast() {
        this(DSL.name("sms_user_event_mast"), null);
    }

    public <O extends Record> SmsUserEventMast(Table<O> child, ForeignKey<O, SmsUserEventMastRecord> key) {
        super(child, key, SMS_USER_EVENT_MAST);
    }

    @Override
    public Schema getSchema() {
        return Sms.SMS;
    }

    @Override
    public UniqueKey<SmsUserEventMastRecord> getPrimaryKey() {
        return Keys.KEY_SMS_USER_EVENT_MAST_PRIMARY;
    }

    @Override
    public List<UniqueKey<SmsUserEventMastRecord>> getKeys() {
        return Arrays.<UniqueKey<SmsUserEventMastRecord>>asList(Keys.KEY_SMS_USER_EVENT_MAST_PRIMARY, Keys.KEY_SMS_USER_EVENT_MAST_IN_SMS_USER_EVENT_MAST_1);
    }

    @Override
    public SmsUserEventMast as(String alias) {
        return new SmsUserEventMast(DSL.name(alias), this);
    }

    @Override
    public SmsUserEventMast as(Name alias) {
        return new SmsUserEventMast(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SmsUserEventMast rename(String name) {
        return new SmsUserEventMast(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SmsUserEventMast rename(Name name) {
        return new SmsUserEventMast(name, null);
    }

    // -------------------------------------------------------------------------
    // Row15 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row15<Long, Long, String, String, String, Integer, Boolean, LocalDateTime, String, String, LocalDateTime, String, String, Integer, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }
}
