/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms.tables.pojos;


import com.gvdroid.simple.jooq.code.sms.tables.interfaces.ISmsUserMast;

import java.time.LocalDateTime;


/**
 * 权限-用户主表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SmsUserMast implements ISmsUserMast {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        name;
    private Integer       category;
    private String        customerid;
    private String        accountno;
    private String        mobile;
    private String        source;
    private String        pincode;
    private LocalDateTime pincodedate;
    private Integer       status;
    private Boolean       deleted;
    private LocalDateTime createdate;
    private String        createuser;
    private String        createorg;
    private LocalDateTime updatedate;
    private String        updateuser;
    private String        updateorg;
    private Integer       updateno;
    private String        entityid;

    public SmsUserMast() {}

    public SmsUserMast(ISmsUserMast value) {
        this.id = value.getId();
        this.name = value.getName();
        this.category = value.getCategory();
        this.customerid = value.getCustomerid();
        this.accountno = value.getAccountno();
        this.mobile = value.getMobile();
        this.source = value.getSource();
        this.pincode = value.getPincode();
        this.pincodedate = value.getPincodedate();
        this.status = value.getStatus();
        this.deleted = value.getDeleted();
        this.createdate = value.getCreatedate();
        this.createuser = value.getCreateuser();
        this.createorg = value.getCreateorg();
        this.updatedate = value.getUpdatedate();
        this.updateuser = value.getUpdateuser();
        this.updateorg = value.getUpdateorg();
        this.updateno = value.getUpdateno();
        this.entityid = value.getEntityid();
    }

    public SmsUserMast(
        Long          id,
        String        name,
        Integer       category,
        String        customerid,
        String        accountno,
        String        mobile,
        String        source,
        String        pincode,
        LocalDateTime pincodedate,
        Integer       status,
        Boolean       deleted,
        LocalDateTime createdate,
        String        createuser,
        String        createorg,
        LocalDateTime updatedate,
        String        updateuser,
        String        updateorg,
        Integer       updateno,
        String        entityid
    ) {
        this.id = id;
        this.name = name;
        this.category = category;
        this.customerid = customerid;
        this.accountno = accountno;
        this.mobile = mobile;
        this.source = source;
        this.pincode = pincode;
        this.pincodedate = pincodedate;
        this.status = status;
        this.deleted = deleted;
        this.createdate = createdate;
        this.createuser = createuser;
        this.createorg = createorg;
        this.updatedate = updatedate;
        this.updateuser = updateuser;
        this.updateorg = updateorg;
        this.updateno = updateno;
        this.entityid = entityid;
    }

    /**
     * Getter for <code>sms.sms_user_mast.id</code>. 主键（用户编号）
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>sms.sms_user_mast.id</code>. 主键（用户编号）
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>sms.sms_user_mast.name</code>. 用户名称
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>sms.sms_user_mast.name</code>. 用户名称
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>sms.sms_user_mast.category</code>. 用户分类 1 user, 2 customer
     */
    @Override
    public Integer getCategory() {
        return this.category;
    }

    /**
     * Setter for <code>sms.sms_user_mast.category</code>. 用户分类 1 user, 2 customer
     */
    @Override
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * Getter for <code>sms.sms_user_mast.customerId</code>. 用户客户编号
     */
    @Override
    public String getCustomerid() {
        return this.customerid;
    }

    /**
     * Setter for <code>sms.sms_user_mast.customerId</code>. 用户客户编号
     */
    @Override
    public void setCustomerid(String customerid) {
        this.customerid = customerid;
    }

    /**
     * Getter for <code>sms.sms_user_mast.accountNo</code>. 商户虚拟账号
     */
    @Override
    public String getAccountno() {
        return this.accountno;
    }

    /**
     * Setter for <code>sms.sms_user_mast.accountNo</code>. 商户虚拟账号
     */
    @Override
    public void setAccountno(String accountno) {
        this.accountno = accountno;
    }

    /**
     * Getter for <code>sms.sms_user_mast.mobile</code>. 用户手机号码
     */
    @Override
    public String getMobile() {
        return this.mobile;
    }

    /**
     * Setter for <code>sms.sms_user_mast.mobile</code>. 用户手机号码
     */
    @Override
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * Getter for <code>sms.sms_user_mast.source</code>. 用户来源 added, invited, machine
     */
    @Override
    public String getSource() {
        return this.source;
    }

    /**
     * Setter for <code>sms.sms_user_mast.source</code>. 用户来源 added, invited, machine
     */
    @Override
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * Getter for <code>sms.sms_user_mast.pinCode</code>. 验证码
     */
    @Override
    public String getPincode() {
        return this.pincode;
    }

    /**
     * Setter for <code>sms.sms_user_mast.pinCode</code>. 验证码
     */
    @Override
    public void setPincode(String pincode) {
        this.pincode = pincode;
    }

    /**
     * Getter for <code>sms.sms_user_mast.pinCodeDate</code>. 验证码时间
     */
    @Override
    public LocalDateTime getPincodedate() {
        return this.pincodedate;
    }

    /**
     * Setter for <code>sms.sms_user_mast.pinCodeDate</code>. 验证码时间
     */
    @Override
    public void setPincodedate(LocalDateTime pincodedate) {
        this.pincodedate = pincodedate;
    }

    /**
     * Getter for <code>sms.sms_user_mast.status</code>. 状态 1 normal
     */
    @Override
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>sms.sms_user_mast.status</code>. 状态 1 normal
     */
    @Override
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * Getter for <code>sms.sms_user_mast.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    @Override
    public Boolean getDeleted() {
        return this.deleted;
    }

    /**
     * Setter for <code>sms.sms_user_mast.deleted</code>. 删除状态 0 正常 1 逻辑删除
     */
    @Override
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * Getter for <code>sms.sms_user_mast.createDate</code>. 创建时间
     */
    @Override
    public LocalDateTime getCreatedate() {
        return this.createdate;
    }

    /**
     * Setter for <code>sms.sms_user_mast.createDate</code>. 创建时间
     */
    @Override
    public void setCreatedate(LocalDateTime createdate) {
        this.createdate = createdate;
    }

    /**
     * Getter for <code>sms.sms_user_mast.createUser</code>. 创建人员
     */
    @Override
    public String getCreateuser() {
        return this.createuser;
    }

    /**
     * Setter for <code>sms.sms_user_mast.createUser</code>. 创建人员
     */
    @Override
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     * Getter for <code>sms.sms_user_mast.createOrg</code>. 创建机构
     */
    @Override
    public String getCreateorg() {
        return this.createorg;
    }

    /**
     * Setter for <code>sms.sms_user_mast.createOrg</code>. 创建机构
     */
    @Override
    public void setCreateorg(String createorg) {
        this.createorg = createorg;
    }

    /**
     * Getter for <code>sms.sms_user_mast.updateDate</code>. 维护时间
     */
    @Override
    public LocalDateTime getUpdatedate() {
        return this.updatedate;
    }

    /**
     * Setter for <code>sms.sms_user_mast.updateDate</code>. 维护时间
     */
    @Override
    public void setUpdatedate(LocalDateTime updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * Getter for <code>sms.sms_user_mast.updateUser</code>. 维护人员
     */
    @Override
    public String getUpdateuser() {
        return this.updateuser;
    }

    /**
     * Setter for <code>sms.sms_user_mast.updateUser</code>. 维护人员
     */
    @Override
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * Getter for <code>sms.sms_user_mast.updateOrg</code>. 维护机构
     */
    @Override
    public String getUpdateorg() {
        return this.updateorg;
    }

    /**
     * Setter for <code>sms.sms_user_mast.updateOrg</code>. 维护机构
     */
    @Override
    public void setUpdateorg(String updateorg) {
        this.updateorg = updateorg;
    }

    /**
     * Getter for <code>sms.sms_user_mast.updateNo</code>. 维护序号
     */
    @Override
    public Integer getUpdateno() {
        return this.updateno;
    }

    /**
     * Setter for <code>sms.sms_user_mast.updateNo</code>. 维护序号
     */
    @Override
    public void setUpdateno(Integer updateno) {
        this.updateno = updateno;
    }

    /**
     * Getter for <code>sms.sms_user_mast.entityId</code>. 所属实体
     */
    @Override
    public String getEntityid() {
        return this.entityid;
    }

    /**
     * Setter for <code>sms.sms_user_mast.entityId</code>. 所属实体
     */
    @Override
    public void setEntityid(String entityid) {
        this.entityid = entityid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SmsUserMast (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(category);
        sb.append(", ").append(customerid);
        sb.append(", ").append(accountno);
        sb.append(", ").append(mobile);
        sb.append(", ").append(source);
        sb.append(", ").append(pincode);
        sb.append(", ").append(pincodedate);
        sb.append(", ").append(status);
        sb.append(", ").append(deleted);
        sb.append(", ").append(createdate);
        sb.append(", ").append(createuser);
        sb.append(", ").append(createorg);
        sb.append(", ").append(updatedate);
        sb.append(", ").append(updateuser);
        sb.append(", ").append(updateorg);
        sb.append(", ").append(updateno);
        sb.append(", ").append(entityid);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ISmsUserMast from) {
        setId(from.getId());
        setName(from.getName());
        setCategory(from.getCategory());
        setCustomerid(from.getCustomerid());
        setAccountno(from.getAccountno());
        setMobile(from.getMobile());
        setSource(from.getSource());
        setPincode(from.getPincode());
        setPincodedate(from.getPincodedate());
        setStatus(from.getStatus());
        setDeleted(from.getDeleted());
        setCreatedate(from.getCreatedate());
        setCreateuser(from.getCreateuser());
        setCreateorg(from.getCreateorg());
        setUpdatedate(from.getUpdatedate());
        setUpdateuser(from.getUpdateuser());
        setUpdateorg(from.getUpdateorg());
        setUpdateno(from.getUpdateno());
        setEntityid(from.getEntityid());
    }

    @Override
    public <E extends ISmsUserMast> E into(E into) {
        into.from(this);
        return into;
    }
}
