spring:
  application:
    name: gvdroid-simple-desire-server
  datasource:
    continue-on-error: false
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
logging:
  level:
    root: info
