/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms;


import com.gvdroid.simple.jooq.code.sms.tables.SmsUserPassport;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in sms.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SMS_USER_PASSPORT_IN_SMS_USER_PASSPORT_2 = Internal.createIndex(DSL.name("in_sms_user_passport_2"), SmsUserPassport.SMS_USER_PASSPORT, new OrderField[] { SmsUserPassport.SMS_USER_PASSPORT.PASSPORTTYPE, SmsUserPassport.SMS_USER_PASSPORT.PASSPORTNO, SmsUserPassport.SMS_USER_PASSPORT.ENTITYID }, false);
}
