/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms;


import com.gvdroid.simple.jooq.code.sms.tables.SmsGroupMast;
import com.gvdroid.simple.jooq.code.sms.tables.SmsGroupRoleXref;
import com.gvdroid.simple.jooq.code.sms.tables.SmsResourceMast;
import com.gvdroid.simple.jooq.code.sms.tables.SmsRoleMast;
import com.gvdroid.simple.jooq.code.sms.tables.SmsRoleResourceXref;
import com.gvdroid.simple.jooq.code.sms.tables.SmsUserEventMast;
import com.gvdroid.simple.jooq.code.sms.tables.SmsUserGroupXref;
import com.gvdroid.simple.jooq.code.sms.tables.SmsUserMast;
import com.gvdroid.simple.jooq.code.sms.tables.SmsUserPassport;
import com.gvdroid.simple.jooq.code.sms.tables.SmsUserRoleXref;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsGroupMastRecord;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsGroupRoleXrefRecord;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsResourceMastRecord;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsRoleMastRecord;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsRoleResourceXrefRecord;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsUserEventMastRecord;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsUserGroupXrefRecord;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsUserMastRecord;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsUserPassportRecord;
import com.gvdroid.simple.jooq.code.sms.tables.records.SmsUserRoleXrefRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * sms.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SmsGroupMastRecord> KEY_SMS_GROUP_MAST_IN_SMS_ORG_MAST_1 = Internal.createUniqueKey(SmsGroupMast.SMS_GROUP_MAST, DSL.name("KEY_sms_group_mast_in_sms_org_mast_1"), new TableField[] { SmsGroupMast.SMS_GROUP_MAST.GROUPID, SmsGroupMast.SMS_GROUP_MAST.ENTITYID }, true);
    public static final UniqueKey<SmsGroupMastRecord> KEY_SMS_GROUP_MAST_PRIMARY = Internal.createUniqueKey(SmsGroupMast.SMS_GROUP_MAST, DSL.name("KEY_sms_group_mast_PRIMARY"), new TableField[] { SmsGroupMast.SMS_GROUP_MAST.GROUPID }, true);
    public static final UniqueKey<SmsGroupRoleXrefRecord> KEY_SMS_GROUP_ROLE_XREF_IN_SMS_GROUP_ROLE_XREF_1 = Internal.createUniqueKey(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF, DSL.name("KEY_sms_group_role_xref_in_sms_group_role_xref_1"), new TableField[] { SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.GROUPID, SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.ROLEID, SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.ENTITYID }, true);
    public static final UniqueKey<SmsGroupRoleXrefRecord> KEY_SMS_GROUP_ROLE_XREF_PRIMARY = Internal.createUniqueKey(SmsGroupRoleXref.SMS_GROUP_ROLE_XREF, DSL.name("KEY_sms_group_role_xref_PRIMARY"), new TableField[] { SmsGroupRoleXref.SMS_GROUP_ROLE_XREF.ID }, true);
    public static final UniqueKey<SmsResourceMastRecord> KEY_SMS_RESOURCE_MAST_IN_SMS_FUNCTION_MAST_1 = Internal.createUniqueKey(SmsResourceMast.SMS_RESOURCE_MAST, DSL.name("KEY_sms_resource_mast_in_sms_function_mast_1"), new TableField[] { SmsResourceMast.SMS_RESOURCE_MAST.ID, SmsResourceMast.SMS_RESOURCE_MAST.ENTITYID }, true);
    public static final UniqueKey<SmsResourceMastRecord> KEY_SMS_RESOURCE_MAST_PRIMARY = Internal.createUniqueKey(SmsResourceMast.SMS_RESOURCE_MAST, DSL.name("KEY_sms_resource_mast_PRIMARY"), new TableField[] { SmsResourceMast.SMS_RESOURCE_MAST.ID }, true);
    public static final UniqueKey<SmsRoleMastRecord> KEY_SMS_ROLE_MAST_IN_SMS_ROLE_MAST_1 = Internal.createUniqueKey(SmsRoleMast.SMS_ROLE_MAST, DSL.name("KEY_sms_role_mast_in_sms_role_mast_1"), new TableField[] { SmsRoleMast.SMS_ROLE_MAST.ID, SmsRoleMast.SMS_ROLE_MAST.ENTITYID }, true);
    public static final UniqueKey<SmsRoleMastRecord> KEY_SMS_ROLE_MAST_PRIMARY = Internal.createUniqueKey(SmsRoleMast.SMS_ROLE_MAST, DSL.name("KEY_sms_role_mast_PRIMARY"), new TableField[] { SmsRoleMast.SMS_ROLE_MAST.ID }, true);
    public static final UniqueKey<SmsRoleResourceXrefRecord> KEY_SMS_ROLE_RESOURCE_XREF_IN_SMS_ROLE_FUNCTION_XREF_1 = Internal.createUniqueKey(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF, DSL.name("KEY_sms_role_resource_xref_in_sms_role_function_xref_1"), new TableField[] { SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.ROLEID, SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.RESOURCEID, SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.ENTITY_ID }, true);
    public static final UniqueKey<SmsRoleResourceXrefRecord> KEY_SMS_ROLE_RESOURCE_XREF_PRIMARY = Internal.createUniqueKey(SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF, DSL.name("KEY_sms_role_resource_xref_PRIMARY"), new TableField[] { SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF.ID }, true);
    public static final UniqueKey<SmsUserEventMastRecord> KEY_SMS_USER_EVENT_MAST_IN_SMS_USER_EVENT_MAST_1 = Internal.createUniqueKey(SmsUserEventMast.SMS_USER_EVENT_MAST, DSL.name("KEY_sms_user_event_mast_in_sms_user_event_mast_1"), new TableField[] { SmsUserEventMast.SMS_USER_EVENT_MAST.ID, SmsUserEventMast.SMS_USER_EVENT_MAST.ENTITYID }, true);
    public static final UniqueKey<SmsUserEventMastRecord> KEY_SMS_USER_EVENT_MAST_PRIMARY = Internal.createUniqueKey(SmsUserEventMast.SMS_USER_EVENT_MAST, DSL.name("KEY_sms_user_event_mast_PRIMARY"), new TableField[] { SmsUserEventMast.SMS_USER_EVENT_MAST.ID }, true);
    public static final UniqueKey<SmsUserGroupXrefRecord> KEY_SMS_USER_GROUP_XREF_IN_SMS_USER_ORG_XREF_1 = Internal.createUniqueKey(SmsUserGroupXref.SMS_USER_GROUP_XREF, DSL.name("KEY_sms_user_group_xref_in_sms_user_org_xref_1"), new TableField[] { SmsUserGroupXref.SMS_USER_GROUP_XREF.USERID, SmsUserGroupXref.SMS_USER_GROUP_XREF.GROUPID, SmsUserGroupXref.SMS_USER_GROUP_XREF.ENTITYID }, true);
    public static final UniqueKey<SmsUserGroupXrefRecord> KEY_SMS_USER_GROUP_XREF_PRIMARY = Internal.createUniqueKey(SmsUserGroupXref.SMS_USER_GROUP_XREF, DSL.name("KEY_sms_user_group_xref_PRIMARY"), new TableField[] { SmsUserGroupXref.SMS_USER_GROUP_XREF.ID }, true);
    public static final UniqueKey<SmsUserMastRecord> KEY_SMS_USER_MAST_IN_SMS_USER_MAST_1 = Internal.createUniqueKey(SmsUserMast.SMS_USER_MAST, DSL.name("KEY_sms_user_mast_in_sms_user_mast_1"), new TableField[] { SmsUserMast.SMS_USER_MAST.ID, SmsUserMast.SMS_USER_MAST.MOBILE, SmsUserMast.SMS_USER_MAST.ENTITYID }, true);
    public static final UniqueKey<SmsUserMastRecord> KEY_SMS_USER_MAST_PRIMARY = Internal.createUniqueKey(SmsUserMast.SMS_USER_MAST, DSL.name("KEY_sms_user_mast_PRIMARY"), new TableField[] { SmsUserMast.SMS_USER_MAST.ID }, true);
    public static final UniqueKey<SmsUserPassportRecord> KEY_SMS_USER_PASSPORT_IN_SMS_USER_PASSPORT_1 = Internal.createUniqueKey(SmsUserPassport.SMS_USER_PASSPORT, DSL.name("KEY_sms_user_passport_in_sms_user_passport_1"), new TableField[] { SmsUserPassport.SMS_USER_PASSPORT.ID, SmsUserPassport.SMS_USER_PASSPORT.ENTITYID }, true);
    public static final UniqueKey<SmsUserPassportRecord> KEY_SMS_USER_PASSPORT_PRIMARY = Internal.createUniqueKey(SmsUserPassport.SMS_USER_PASSPORT, DSL.name("KEY_sms_user_passport_PRIMARY"), new TableField[] { SmsUserPassport.SMS_USER_PASSPORT.ID }, true);
    public static final UniqueKey<SmsUserRoleXrefRecord> KEY_SMS_USER_ROLE_XREF_IN_SMS_USER_ROLE_XREF_1 = Internal.createUniqueKey(SmsUserRoleXref.SMS_USER_ROLE_XREF, DSL.name("KEY_sms_user_role_xref_in_sms_user_role_xref_1"), new TableField[] { SmsUserRoleXref.SMS_USER_ROLE_XREF.ROLEID, SmsUserRoleXref.SMS_USER_ROLE_XREF.USERID, SmsUserRoleXref.SMS_USER_ROLE_XREF.ENTITYID }, true);
    public static final UniqueKey<SmsUserRoleXrefRecord> KEY_SMS_USER_ROLE_XREF_PRIMARY = Internal.createUniqueKey(SmsUserRoleXref.SMS_USER_ROLE_XREF, DSL.name("KEY_sms_user_role_xref_PRIMARY"), new TableField[] { SmsUserRoleXref.SMS_USER_ROLE_XREF.ID }, true);
}
