/*
 * This file is generated by jOOQ.
 */
package com.gvdroid.simple.jooq.code.sms;


import com.gvdroid.simple.jooq.code.sms.tables.SmsGroupMast;
import com.gvdroid.simple.jooq.code.sms.tables.SmsGroupRoleXref;
import com.gvdroid.simple.jooq.code.sms.tables.SmsResourceMast;
import com.gvdroid.simple.jooq.code.sms.tables.SmsRoleMast;
import com.gvdroid.simple.jooq.code.sms.tables.SmsRoleResourceXref;
import com.gvdroid.simple.jooq.code.sms.tables.SmsUserEventMast;
import com.gvdroid.simple.jooq.code.sms.tables.SmsUserGroupXref;
import com.gvdroid.simple.jooq.code.sms.tables.SmsUserMast;
import com.gvdroid.simple.jooq.code.sms.tables.SmsUserPassport;
import com.gvdroid.simple.jooq.code.sms.tables.SmsUserRoleXref;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sms extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sms</code>
     */
    public static final Sms SMS = new Sms();

    /**
     * 权限-用户分组主表
     */
    public final SmsGroupMast SMS_GROUP_MAST = SmsGroupMast.SMS_GROUP_MAST;

    /**
     * 权限-用户分组角色关联表
     */
    public final SmsGroupRoleXref SMS_GROUP_ROLE_XREF = SmsGroupRoleXref.SMS_GROUP_ROLE_XREF;

    /**
     * 权限-权限主表
     */
    public final SmsResourceMast SMS_RESOURCE_MAST = SmsResourceMast.SMS_RESOURCE_MAST;

    /**
     * 权限-角色主表
     */
    public final SmsRoleMast SMS_ROLE_MAST = SmsRoleMast.SMS_ROLE_MAST;

    /**
     * 权限-角色资源关联表
     */
    public final SmsRoleResourceXref SMS_ROLE_RESOURCE_XREF = SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF;

    /**
     * 权限-用户事件主表
     */
    public final SmsUserEventMast SMS_USER_EVENT_MAST = SmsUserEventMast.SMS_USER_EVENT_MAST;

    /**
     * 权限-用户用户组关联表
     */
    public final SmsUserGroupXref SMS_USER_GROUP_XREF = SmsUserGroupXref.SMS_USER_GROUP_XREF;

    /**
     * 权限-用户主表
     */
    public final SmsUserMast SMS_USER_MAST = SmsUserMast.SMS_USER_MAST;

    /**
     * 权限-用户登陆凭证
     */
    public final SmsUserPassport SMS_USER_PASSPORT = SmsUserPassport.SMS_USER_PASSPORT;

    /**
     * 权限-用户角色关联表
     */
    public final SmsUserRoleXref SMS_USER_ROLE_XREF = SmsUserRoleXref.SMS_USER_ROLE_XREF;

    /**
     * No further instances allowed
     */
    private Sms() {
        super("sms", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            SmsGroupMast.SMS_GROUP_MAST,
            SmsGroupRoleXref.SMS_GROUP_ROLE_XREF,
            SmsResourceMast.SMS_RESOURCE_MAST,
            SmsRoleMast.SMS_ROLE_MAST,
            SmsRoleResourceXref.SMS_ROLE_RESOURCE_XREF,
            SmsUserEventMast.SMS_USER_EVENT_MAST,
            SmsUserGroupXref.SMS_USER_GROUP_XREF,
            SmsUserMast.SMS_USER_MAST,
            SmsUserPassport.SMS_USER_PASSPORT,
            SmsUserRoleXref.SMS_USER_ROLE_XREF);
    }
}
